/* ══════════════════════════════════════════════
   DATA — البيانات فقط، لا دوال هنا
   لتحديث المحتوى: عدّل هذا الملف فقط
   ══════════════════════════════════════════════ */

const PG = [
  { id: "home", n: "الرئيسية", ic: "🏠" },
  { id: "projects", n: "المشاريع", ic: "🚀" },
  { id: "map", n: "الخريطة", ic: "🗺️" },
  { id: "auto", n: "الأتمتة", ic: "⚙️" },
  { id: "server", n: "السيرفر", ic: "🖥️" },
  { id: "bots", n: "البوتات", ic: "🤖" },
  { id: "tools", n: "الأدوات", ic: "🛠️" },
  { id: "ideas", n: "الأفكار", ic: "💡" },
  { id: "cloud", n: "السحابية", ic: "☁️" },
  { id: "archive", n: "الأرشيف", ic: "🗄️" },
];

const DATA_TRUST_MODEL = {
  project: {
    source: "ملفات المصدر + git + المسارات الفعلية + فحص نشر عند توفره",
    refresh_mode: "runtime-audit",
    stale_after: "14d",
    auto_refresh: "نشط الآن: git + deploy + filesystem check كل 6 ساعات",
  },
  service: {
    source: "runtime على السيرفر",
    refresh_mode: "runtime-audit",
    stale_after: "3d",
    auto_refresh: "نشط الآن: ssh + docker + systemd + cron كل 6 ساعات",
  },
  tool: {
    source: "ملفات الإعداد والجرد المحلي المؤكد",
    refresh_mode: "file-audit",
    stale_after: "7d",
    auto_refresh:
      "نشط الآن: config/filesystem checks كل 6 ساعات عند توفر دليل مباشر",
  },
  cloud: {
    source: "ربط يدوي مع probes نوعية حسب كل منصة",
    refresh_mode: "runtime-audit",
    stale_after: "14d",
    auto_refresh:
      "نشط الآن: ssh/http/git/filesystem checks كل 6 ساعات بحسب كل عنصر",
  },
  bot: {
    source: "runtime/config حسب النوع",
    refresh_mode: "runtime-audit",
    stale_after: "7d",
    auto_refresh:
      "نشط الآن: runtime + filesystem checks كل 6 ساعات؛ فحص القناة ليس شاملًا بعد",
  },
  idea: {
    source: "تحرير يدوي",
    refresh_mode: "manual-curation",
    stale_after: "30d",
    auto_refresh: "future: review queue",
  },
  archive: {
    source: "catalog يدوي",
    refresh_mode: "file-audit",
    stale_after: "60d",
    auto_refresh:
      "نشط الآن: existence-check للمسارات المعروفة كل 6 ساعات؛ معنى المحتوى يبقى يدويًا",
  },
};

const PRJ = [
  {
    name: "BRIX Travel System",
    id: "brix-travel-system",
    kind: "product",
    ar: "نظام حجز الفنادق",
    st: "a",
    em: "🏨",
    cl: "#6C3AED",
    pct: 92,
    summary: "النظام الرئيسي لإدارة عقود الفنادق والتسعير والبحث والنتائج، مع بوت تلجرام مرتبط ١٠٠٪ بنفس محرك الأسعار.",
    local_path:
      "/Users/rabeeshaban/Desktop/Projects/🏨 BRIX-Travel/hotel-web-app",
    server_path: null,
    repo_url: "https://github.com/aneerabee/brix-travel-system",
    deploy_url: "https://brix-hotel-web-app-production.up.railway.app",
    stack: [
      "Next.js 16",
      "TypeScript",
      "Supabase",
      "Vitest",
      "Playwright",
      "Tailwind 4",
    ],
    subsystems: [
      "pricing-engine",
      "contract-wizard",
      "contract-edit",
      "results-ui",
      "api-layer",
      "alerts-dashboard",
      "telegram-bot",
      "time-machine",
      "daily-backup",
    ],
    related_services: ["telegram-bot @BrixPrice_bot"],
    related_tools: [],
    related_cloud: ["GitHub", "Supabase", "Railway", "Telegram"],
    ops: [
      "النشر التلقائي على Railway من فرع main",
      "Supabase هو مصدر الحقيقة الوحيد (v15.0+)",
      "النسخ الاحتياطي اليومي إلى مستودع brix-backups كل ٠٢:٠٠ صباحاً",
    ],
    desc: "المشروع الرئيسي — نظام إدارة عقود الفنادق وحساب الأسعار، مع بوت تلجرام @BrixPrice_bot مرتبط بنفس محرك التسعير.\n\nالتقنيات:\nNext.js 16 + React 18 + TypeScript 5.9 + Tailwind 4\nSupabase (PostgreSQL) + Zod 4 + Vitest + Playwright\n\nالأرقام:\nألفان واثنا عشر اختبار يمر، صفر ثغرات حرجة\nعشر خطوات لإدخال عقد جديد\nستة خطوات في تدفّق البوت\nترجمة كاملة عربي وإنجليزي\n\nسير البيانات:\nالمستعمل يدخل العقد من شاشة إدخال العقود ← Supabase ← محرك التسعير ← يرد على البوت أو على صفحة البحث في الموقع\n\nالنشر: ريلواي حي وشغّال، آخر تحديث اليوم ٢٠٢٦-٠٥-١١، يطابق ١٠٠٪ ما يعرضه البوت.",
    tags: [
      "Next.js 16",
      "Supabase",
      "Tailwind 4",
      "Vitest",
      "Playwright",
      "TypeScript",
    ],
    path: "/Users/rabeeshaban/Desktop/Projects/🏨 BRIX-Travel/hotel-web-app",
    links: {
      "النظام الحي":
        "https://brix-hotel-web-app-production.up.railway.app",
      "البحث عن أسعار":
        "https://brix-hotel-web-app-production.up.railway.app/search",
      "إدخال عقد جديد":
        "https://brix-hotel-web-app-production.up.railway.app/contract-wizard",
      "قائمة العقود":
        "https://brix-hotel-web-app-production.up.railway.app/contracts",
      "بوت تلجرام":
        "https://t.me/BrixPrice_bot",
      "النسخ الاحتياطي اليومي":
        "https://github.com/aneerabee/brix-backups",
      "آخر تشغيل نسخ":
        "https://github.com/aneerabee/brix-travel-system/actions/workflows/daily-contract-backup.yml",
      Railway: "https://railway.com/project/2af4cb7e-f4ef-4de0-b86c-b4957fac185f",
      GitHub: "https://github.com/aneerabee/brix-travel-system",
      Supabase: "https://supabase.com/dashboard/project/fiancnwrfehyrkvfjwfq",
    },
    links_desc: {
      "النظام الحي":
        "الواجهة الرئيسية للنظام (تحوّل تلقائياً إلى صفحة البحث)",
      "البحث عن أسعار":
        "محرك البحث — ابحث بفندق وتاريخ وعدد ضيوف لتحصل على السعر",
      "إدخال عقد جديد":
        "شاشة إدخال عقد فندق بعشر خطوات، يطلب تسجيل الدخول",
      "قائمة العقود":
        "كل العقود المحفوظة، للمراجعة والتعديل والحذف، يطلب تسجيل الدخول",
      "بوت تلجرام":
        "بوت بحث الأسعار للوكلاء، يعطي نفس النتيجة بالضبط التي يعطيها الويب. ست خطوات بالأزرار، عربي أو إنجليزي.",
      "النسخ الاحتياطي اليومي":
        "مستودع خاص فيه نسخة كاملة من كل جداول العقود ليوم. تحقق منه أسبوعياً — يجب أن ترى مجلد ديلي بتاريخ كل يوم.",
      "آخر تشغيل نسخ":
        "صفحة سجل تشغيلات النسخ اليومي. اللون الأخضر يعني نجح، الأحمر يعني فشل — لو فشل افتحه واطّلع على السبب.",
      Railway:
        "لوحة النشر، اللوغات، المتغيرات، الفروع، إعادة التشغيل",
      GitHub:
        "الكود المصدري — Next.js 16 و Supabase وبوت تلجرام وألفين اختبار يمر",
      Supabase:
        "قاعدة البيانات — جداول العقود والفترات والأسعار والخصومات ومضاعفات الإشغال",
    },
    current_status: {
      updated: "2026-05-11",
      where:
        "النظام حي ومنشور على ريلواي ومرتبط بالكامل ببوت تلجرام. البوت يعيد نفس الأسعار من نفس الفنادق بنفس التواريخ التي يعيدها الويب، تحقق منها بعشرين سيناريو حجز معقد وعشرين حالة حافة. الترجمة كاملة عربي وإنجليزي، الأزرار ملوّنة بنظام موحّد، النتائج تظهر في صناديق قابلة للتوسيع للتفاصيل. ألفان واثنا عشر اختبار وحدوي يمر، صفر ثغرات حرجة. تم تفعيل ثلاث طبقات حماية لجدول مضاعفات الإشغال الذي ضاع قبلاً من فندق سوينو: الأولى هي آلة الزمن داخل الموقع التي تأخذ صورة قبل وبعد كل عملية حفظ، الثانية هي النسخ اليومي على غيت هب الذي يحفظ كل الجداول في مستودع منفصل اسمه بريكس باك آبس في الساعة الثانية صباحاً، الثالثة هي حماية برمجية ترفض أي طلب حفظ بقائمة فارغة إلا مع تأكيد صريح من المستعمل.",
      next_step:
        "أولاً، تحقق دورياً من أن طبقات الحماية الثلاث ما زالت تعمل. ادخل مستودع بريكس باك آبس على غيت هب وتأكد أن نسخة اليوم موجودة في مجلد ديلي بتاريخ اليوم. لو ما وُجدت اذهب لتاب أكشنز في مستودع بريكس ترافل سيستم واطّلع على آخر تشغيل لـدايلي كونتراكت باك آب. ثانياً، تحقق من شاشة آلة الزمن في الموقع لكل فندق تعدّله، يجب أن ترى صورتين جديدتين بعد كل حفظ. ثالثاً، أعد إدخال مضاعفات إشغال فندق سوينو من شاشة تعديل العقود لأن الجدول حالياً صفر صفوف. رابعاً، أدخل بقية العقود التسعة من ملفات بي دي إف.",
      blockers: [
        {
          text: "تذكير دائم — تحقق أسبوعياً من نسخ غيت هب اليومية في مستودع بريكس باك آبس، يجب أن يكون هناك مجلد جديد بتاريخ كل يوم. لو غاب يومان متتاليان يعني الحماية معطّلة وتحتاج فحص.",
          priority: "high",
        },
        {
          text: "تذكير دائم — قبل ضغط حفظ المضاعفات في شاشة تعديل العقود، تأكد أن القائمة فيها صفوف. حفظ بقائمة فارغة محمي الآن لكن لا تعتمد فقط على الحماية.",
          priority: "high",
        },
        {
          text: "مضاعفات إشغال فندق سوينو ديلوكس — الجدول حالياً صفر صفوف، يحتاج إعادة إدخال من شاشة تعديل العقود. الباقي من العقد سليم سبع غرف وعشر فترات وسبعين سعر أساسي.",
          priority: "high",
        },
        {
          text: "اثنتان وعشرون قيمة سعة غرف خاطئة في ريكسوس (ماكس تشيلدرن وماكس انفنتس) — لا تؤثر على السعر لكنها تسمح بحجوزات بتركيبات خارج العقد",
          priority: "med",
        },
        {
          text: "تسعة عقود فندقية في data/contracts كملفات بي دي إف لم تُدخل بعد في النظام (ماكس رويال، ريغنوم، إيلا، كاليستا، إلخ)",
          priority: "med",
        },
      ],
      use_guide:
        "للاستخدام اليومي ابحث من البوت أو من صفحة البحث في الموقع، الاثنان يعطيان نفس النتيجة. لإدخال عقد فندق جديد من شاشة إدخال العقود، سجّل الدخول برمز الإدارة وامرّ على الخطوات العشر. لتعديل عقد ادخل قائمة العقود واختر تعديل. للتحقق من الحماية افتح مستودع بريكس باك آبس على غيت هب وانظر تاريخ آخر مجلد ديلي، أو افتح شاشة آلة الزمن في الموقع وانظر عدد الصور لكل فندق. لاستعادة بيانات ضاعت ادخل آلة الزمن واختر صورة قبل الحادثة ثم اضغط استعادة.",
    },
    claude_session: {
      session_name: "[brix system]",
      terminal: "iTerm2",
      cwd: "/Users/rabeeshaban/Desktop/Projects/🏨 BRIX-Travel/hotel-web-app",
      command:
        "cd ~/Desktop/Projects/🏨\\ BRIX-Travel/hotel-web-app && claude",
      memory_file:
        "~/.claude/projects/-Users-rabeeshaban-Desktop-Projects----BRIX-Travel/memory/MEMORY.md",
      note: "بعد فتح كلود اكتب رزيوم واختر الجلسة المسماة بريكس سيستم. آخر نقطة: إصلاحات شاملة تمّت محلياً برقم 9a1251a5 تنتظر إذن الدفع. ملف الذاكرة يحوي ثلاثة عشر ملفاً منظّماً يشمل القرارات التجارية المأخوذة في 5 مايو.",
    },
  },
  {
    name: "EasyBooking",
    id: "easybooking",
    kind: "umbrella",
    ar: "تسويق إيزي بوكينغ",
    st: "a",
    em: "📢",
    cl: "#2563EB",
    pct: 60,
    summary:
      "منظومة تسويق وتشغيل تضم حملات Meta وCRM واتساب وخادم MCP داخلي وأدوات ومحتوى حملات.",
    local_path: "/Users/rabeeshaban/Desktop/Projects/📢 EasyBooking",
    server_path: null,
    repo_url: null,
    deploy_url: null,
    stack: ["Meta Ads", "WhatsApp", "Python", "MCP", "Assets"],
    subsystems: [
      "whatsapp-crm",
      "meta-mcp",
      "social-tools",
      "docs",
      "sueno-scripts",
    ],
    related_services: ["Chrome Headless"],
    related_tools: ["Meta MCP"],
    related_cloud: ["Meta Business", "Railway", "GitHub", "iCloud Drive"],
    ops: ["إدارة حملات متعددة الأسواق", "أصول وصور ومحتوى محفوظة على iCloud"],
    desc: "ذراع التسويق لـ BRIX TRAVEL — حجوزات فنادق\n\n🎯 الحملة الحالية:\nSueno Deluxe Belek — 6 مناطق\nشمال أفريقيا → الخليج → الشام → عرب تركيا → أوروبا → كندا\n8 كاروسيلات + 5 فيديوهات\nنسخ عربي فقط\n\n📱 القنوات:\nMeta Business Suite + Ads Manager\nWhatsApp كقناة حجز أساسية\nInstagram + Facebook\n\n🛠️ أدوات:\n37 أداة MCP للتحكم بالإعلانات\nSocial Growth Tracker\nحساب: act_840190289038740",
    tags: ["Meta Ads", "WhatsApp", "6 دول", "37 MCP Tools", "Instagram"],
    path: "/Users/rabeeshaban/Desktop/Projects/📢 EasyBooking",
    links: {
      "Ads Manager":
        "https://adsmanager.facebook.com/adsmanager/manage/campaigns?act=840190289038740",
      "Business Suite": "https://business.facebook.com",
    },
  },
  {
    name: "Meta MCP",
    id: "meta-mcp",
    kind: "internal-tool",
    ar: "خادم MCP للإعلانات",
    st: "a",
    em: "🤖",
    cl: "#2563EB",
    pct: 88,
    summary:
      "خادم MCP داخلي مطور خصيصًا للتحكم في إعلانات Meta عبر وحدات قراءة وكتابة واستهداف ونسخ وتحويلات.",
    local_path: "/Users/rabeeshaban/Developer/meta-mcp",
    server_path: null,
    repo_url: "https://github.com/aneerabee/meta-mcp",
    deploy_url: null,
    stack: ["Python", "MCP", "httpx", "Meta Graph API"],
    subsystems: [
      "read",
      "write",
      "targeting",
      "duplicate",
      "conversions",
      "utility",
    ],
    related_services: [],
    related_tools: ["Claude Code"],
    related_cloud: ["GitHub", "Meta Business"],
    parent_project: "EasyBooking",
    ops: ["أداة تشغيل داخلية وليست SaaS", "تتحكم بحساب Meta Ads مباشرة"],
    desc: "خادم MCP داخلي لإدارة إعلانات Meta عبر وحدات مستقلة\n\n📦 الوحدات:\nread.py · write.py · targeting.py\nduplicate.py · conversions.py · utility.py\n\n🔧 التقنيات:\nPython + MCP stdio + httpx\nMeta Graph API\n\n🎯 الاستخدام:\nقراءة الحملات والإعلانات\nإنشاء وتعديل ونسخ الأصول\nإدارة الاستهداف والتحويلات\n\n🔒 الريبو خاص على GitHub",
    tags: ["Python", "MCP", "Meta Graph API", "httpx", "Internal Tool"],
    path: "/Users/rabeeshaban/Developer/meta-mcp",
    links: { GitHub: "https://github.com/aneerabee/meta-mcp" },
  },
  {
    name: "Wapy.dev",
    id: "wapy-dev",
    kind: "product",
    ar: "متتبع الاشتراكات",
    st: "a",
    em: "💳",
    cl: "#10B981",
    pct: 55,
    summary:
      "تطبيق اشتراكات حي يعمل عبر Docker بثلاث حاويات على السيرفر مع نسخ احتياطي وتنظيف مجدول.",
    local_path: null,
    server_path: "/opt/wapy",
    repo_url: null,
    deploy_url: "http://100.116.69.101:3000",
    stack: [
      "Next.js",
      "React",
      "Prisma",
      "PostgreSQL",
      "Paddle",
      "Better Auth",
      "Docker",
    ],
    subsystems: ["app", "cron", "db", "backup", "media"],
    related_services: [
      "Wapy App",
      "Wapy Cron",
      "Wapy DB",
      "Wapy Backup",
      "Wapy Cleanup",
    ],
    related_tools: [],
    related_cloud: ["Contabo VPS", "Tailscale"],
    ops: [
      "backup يوميًا 3 صباحًا",
      "cleanup يوميًا 4 صباحًا",
      "تشغيل عبر Docker",
    ],
    desc: "تطبيق تتبع وإدارة الاشتراكات الشهرية\n\n🔧 التقنيات:\nNext.js + Turbopack + TypeScript\nPrisma ORM + PostgreSQL 17.5\nPaddle (دفع) + better-auth (مصادقة)\nTailwind + shadcn/ui\n\n🐳 Docker:\n3 حاويات: app + db + cron\nالمنفذ: 3000 (عبر Tailscale فقط)\n\n💾 النسخ الاحتياطي:\nيومياً 3 صباحاً + تنظيف 4 صباحاً\nاحتفاظ 30 يوم · حد 50 ملف\n\n👤 المؤلف: ربيع · الإصدار: 2.0.0",
    tags: ["Next.js", "Prisma", "Docker", "PostgreSQL", "Paddle", "shadcn/ui"],
    path: "server:/opt/wapy",
    links: { "التطبيق الداخلي": "http://100.116.69.101:3000" },
  },
  {
    name: "Command Center",
    id: "command-center",
    kind: "dashboard",
    ar: "مركز التحكم",
    st: "a",
    em: "⚡",
    cl: "#F59E0B",
    pct: 90,
    summary:
      "لوحة تحكم شخصية تعرض المشاريع والخدمات والبوتات والأدوات والسحابية من مكان واحد.",
    local_path: "/tmp/cc-push",
    server_path: null,
    repo_url: "https://github.com/aneerabee/command-center",
    deploy_url: "https://aneerabee.github.io/command-center/",
    stack: ["HTML", "CSS", "JavaScript", "GitHub Pages"],
    subsystems: [
      "home",
      "projects",
      "map",
      "auto",
      "server",
      "bots",
      "tools",
      "ideas",
      "cloud",
      "archive",
    ],
    related_services: [],
    related_tools: [],
    related_cloud: ["GitHub"],
    ops: ["نشر ثابت عبر GitHub Pages", "صفحات متعددة مع render client-side"],
    desc: "لوحة تحكم واحدة تجمع كل شيء\n\n📄 4 ملفات (HTML + CSS + JS + Data)\n10 صفحات بتصاميم مختلفة\n5 أنماط عرض تفصيلية فريدة\n📱 متجاوب + GitHub Pages",
    tags: ["HTML", "CSS", "JS", "GitHub Pages"],
    path: "github:aneerabee/command-center",
    links: {
      الموقع: "https://aneerabee.github.io/command-center/",
      GitHub: "https://github.com/aneerabee/command-center",
    },
  },
  {
    name: "WhatsApp CRM",
    id: "whatsapp-crm",
    kind: "service-app",
    ar: "نظام إدارة العملاء",
    st: "a",
    em: "💬",
    cl: "#25D366",
    pct: 45,
    summary:
      "FastAPI backend فعلي لإدارة محادثات واتساب والحجوزات والـ CAPI ضمن منظومة EasyBooking.",
    local_path:
      "/Users/rabeeshaban/Desktop/Projects/📢 EasyBooking/💬 whatsapp-crm",
    server_path: null,
    repo_url: "https://github.com/aneerabee/easybooking-whatsapp-crm",
    deploy_url:
      "https://easybooking-whatsapp-crm-production.up.railway.app/#inbox",
    stack: [
      "FastAPI",
      "Python",
      "PostgreSQL",
      "Meta CAPI",
      "WhatsApp Cloud API",
      "Docker",
      "Railway",
    ],
    subsystems: ["dashboard", "data", "config", "scripts", "tools"],
    related_services: [],
    related_tools: [],
    related_cloud: ["Railway", "Meta Business", "GitHub"],
    parent_project: "EasyBooking",
    ops: ["production على Railway", "API + dashboard + webhooks"],
    desc: "قلب نظام التحويل — إعلان → واتساب → حجز\n\n🔄 المسار:\nإعلان Meta (CTWA) → نقرة العميل\n→ رسالة واتساب تلقائية (60 ثانية)\n→ 8 قوالب عربية حسب زاوية الإعلان\n→ متابعة → حجز → تتبع ROAS\n\n📊 قاعدة البيانات:\ncontacts · conversations · messages\nbookings · meta_events_log · raw_webhooks\n\n🔧 API: 8 نقاط نهاية + X-API-Key\n\n📈 تتبع التحويلات:\nMeta CAPI مع EMQ scoring\nattribution: إعلان → واتساب → حجز → قيمة\n\n🌍 6 دول: ليبيا، مصر، العراق، تونس، المغرب، الجزائر\n\n🔧 التقنيات:\nFastAPI + PostgreSQL + Meta CAPI\nWhatsApp Cloud API + Docker\nRailway (production)",
    tags: [
      "FastAPI",
      "Meta CAPI",
      "WhatsApp",
      "Railway",
      "PostgreSQL",
      "Docker",
    ],
    path: "/Users/rabeeshaban/Desktop/Projects/📢 EasyBooking/💬 whatsapp-crm",
    links: {
      "لوحة التحكم":
        "https://easybooking-whatsapp-crm-production.up.railway.app/#inbox",
      "صفحة الربط":
        "https://easybooking-whatsapp-crm-production.up.railway.app/signup",
      GitHub: "https://github.com/aneerabee/easybooking-whatsapp-crm",
      Railway: "https://railway.com/dashboard",
      "Meta Console":
        "https://developers.facebook.com/apps/1424331552514758/dashboard/",
      "API Setup":
        "https://developers.facebook.com/apps/1424331552514758/whatsapp-business/wa-dev-console/",
      "WhatsApp Manager": "https://business.facebook.com/wa/manage/",
      "Events Manager":
        "https://business.facebook.com/events_manager2/list/pixel/",
      "App Review":
        "https://developers.facebook.com/apps/1424331552514758/app-review/",
    },
    links_desc: {
      "لوحة التحكم":
        "الإنبوكس الحي — مشاهدة المحادثات والحجوزات وإدارة الفريق",
      "صفحة الربط": "ربط رقم واتساب جديد عبر Embedded Signup",
      GitHub: "الكود المصدري الكامل — FastAPI + dashboard",
      Railway: "لوحة النشر — اللوغات، المتغيرات، إعادة التشغيل",
      "Meta Console":
        "EasyBooking-API (App ID 1424331552514758) — الإعدادات الأساسية",
      "API Setup":
        "إرسال رسائل تجريبية وأخذ التوكن — يُستخدم في الفيديو الأول",
      "WhatsApp Manager":
        "إدارة الأرقام، إنشاء قوالب الرسائل — يُستخدم في الفيديو الثاني",
      "Events Manager":
        "للحصول على META_PIXEL_ID المفقود (عائق حرج)",
      "App Review":
        "تقديم طلب Advanced Access ورفع الفيديوهين بعد التسجيل",
    },
    current_status: {
      updated: "2026-05-05",
      where:
        "النظام مبني بالكامل ومنشور على Railway ويعمل (58 endpoint، 13+ جدول، لوحة تحكم، 14 أداة MCP، CAPI جاهز). توقفنا في 28 مارس عند مرحلة مراجعة التطبيق عند ميتا.",
      next_step:
        "تسجيل فيديوهين لمراجعة التطبيق: (1) إرسال واستقبال رسالة، (2) إنشاء قالب booking_confirmation. ثم رفعهما في صفحة App Review.",
      blockers: [
        {
          text: "META_PIXEL_ID مفقود — أحداث CAPI لا تُرسل بدونه (يُؤخذ من Events Manager)",
          priority: "high",
        },
        {
          text: "Standard Access فقط — يلزم Advanced Access للإرسال لأي رقم (يحتاج الفيديوهين + مراجعة التطبيق)",
          priority: "high",
        },
        {
          text: "BRIX غير مسجّلة كمزوّد تقني — حل سريع: اشتراك بـ Wati ($59/شهر) أو respond.io ($79)",
          priority: "med",
        },
        {
          text: "الرقم التجريبي محدود — فقط أرقام مسجّلة مسبقاً يمكنها المراسلة",
          priority: "low",
        },
      ],
      use_guide:
        "للاستخدام اليومي: افتح 'لوحة التحكم' لمتابعة المحادثات والحجوزات. للتطوير: افتح Core Shell ونفّذ أمر استئناف Claude بالأسفل. للنشر: ادفع لـ GitHub والنشر تلقائي عبر Railway.",
    },
    claude_session: {
      session_name: "[crm whats brix]",
      terminal: "Core Shell",
      cwd: "/Users/rabeeshaban/Desktop/Projects/📢 EasyBooking/💬 whatsapp-crm",
      command:
        "cd ~/Desktop/Projects/📢\\ EasyBooking/💬\\ whatsapp-crm && claude",
      memory_file:
        "~/.claude/projects/-Users-rabeeshaban/memory/whatsapp-crm-full-status.md",
      note: "بعد فتح Claude اكتب /resume واختر الجلسة المسماة [crm whats brix] لمتابعة آخر نقطة وصلنا لها (تسجيل فيديوهات مراجعة ميتا).",
    },
  },
  {
    name: "Money Manager",
    id: "money-manager",
    kind: "financial-app",
    ar: "مدير المال",
    st: "p",
    em: "💰",
    cl: "#F59E0B",
    pct: 40,
    summary:
      "تطبيق/API مالي مستقل مبني بـ FastAPI ومربوط بـ Supabase وأسعار مالية خارجية.",
    local_path: "/Users/rabeeshaban/Desktop/Projects/💰 Money-Manager",
    server_path: null,
    repo_url: "https://github.com/aneerabee/money-manager",
    deploy_url: null,
    stack: ["FastAPI", "Python", "Supabase", "CoinGecko", "Alpha Vantage"],
    subsystems: ["main-api"],
    related_services: [],
    related_tools: ["Claude Code"],
    related_cloud: ["GitHub", "Supabase", "CoinGecko"],
    ops: [
      "مشروع متوقف حاليًا لكنه قائم كمصدر كود فعال",
      "يعتمد على APIs خارجية مالية",
    ],
    desc: "نظام إدارة مالية شامل\n\n💹 الميزات:\nأسعار كريبتو لحظية (CoinGecko)\nأسعار أسهم (Alpha Vantage)\nCRUD كامل للمعاملات\nتخزين مؤقت ذكي\n\n🔧 التقنيات:\nFastAPI + Python\nSupabase (PostgreSQL)\nCoinGecko + Alpha Vantage APIs\n\n📂 ملف رئيسي: main.py (102 KB)",
    tags: ["FastAPI", "Supabase", "CoinGecko", "Python", "Alpha Vantage"],
    path: "/Users/rabeeshaban/Desktop/Projects/💰 Money-Manager",
    links: { GitHub: "https://github.com/aneerabee/money-manager" },
  },
  {
    name: "BRIX Travel Website",
    id: "brix-travel-website",
    kind: "website",
    ar: "موقع بريكس ترافل",
    st: "a",
    em: "🌐",
    cl: "#E8453C",
    pct: 30,
    summary: "موقع WordPress حي للشركة، وليس مجرد static landing page.",
    local_path: "/Users/rabeeshaban/Desktop/Projects/🌐 brixtravelwebsite",
    server_path: null,
    repo_url: "https://github.com/aneerabee/brixtravel",
    deploy_url: null,
    stack: ["WordPress", "PHP", "HTML", "CSS", "JavaScript"],
    subsystems: ["wp-admin", "wp-content", "wp-includes", "assets"],
    related_services: [],
    related_tools: [],
    related_cloud: ["GitHub", "Hostinger"],
    ops: ["موقع حي يحتاج تحديث محتوى وتطوير واجهة حجز"],
    desc: "الموقع الرسمي لشركة BRIX TRAVEL — مباشر على Hostinger\n\n🌍 عربي + إنجليزي · اكتشاف تلقائي للغة\n📱 تصميم متجاوب · Google Maps مدمج\nWhatsApp + Instagram + Facebook\n\n🔧 التقنيات:\nHTML/CSS/JS + PHP + WordPress\n\n🎨 الهوية البصرية:\nBrix Travel.ai + .eps (شعار كامل)\n\n🛠️ يحتاج تطوير:\nواجهة حجز مباشرة · تحديث المحتوى\n\n📡 النشر: Hostinger",
    tags: ["WordPress", "PHP", "Hostinger", "HTML", "يحتاج تطوير"],
    path: "/Users/rabeeshaban/Desktop/Projects/🌐 brixtravelwebsite",
    links: { GitHub: "https://github.com/aneerabee/brixtravel" },
  },
  {
    name: "Chess Academy",
    id: "chess-academy",
    kind: "content-product",
    ar: "أكاديمية الشطرنج",
    st: "a",
    em: "♟️",
    cl: "#d4a843",
    pct: 95,
    summary:
      "منتج تعليمي static ثنائي اللغة منشور على GitHub Pages مع نظام تقدم واختبارات.",
    local_path: null,
    server_path: null,
    repo_url: "https://github.com/aneerabee/chess-academy",
    deploy_url: "https://aneerabee.github.io/chess-academy/",
    stack: ["HTML", "CSS", "JavaScript", "GitHub Pages"],
    subsystems: [
      "arabic-app",
      "english-app",
      "landing-en",
      "quiz-system",
      "xp-system",
    ],
    related_services: [],
    related_tools: [],
    related_cloud: ["GitHub"],
    ops: ["بيع Freemium", "نشر مباشر على GitHub Pages"],
    desc: "دليل شطرنج تفاعلي — عربي + إنجليزي\n\n🔧 التقنيات:\nHTML + CSS + Vanilla JS\nتصميم داكن/ذهبي · بدون خادم\n\n📊 المحتوى:\n6 مراحل × لغتين (عربي + إنجليزي)\n30+ مفهوم وتكتيك\nاختبارات تفاعلية بعد كل مرحلة\nتمارين «فكّر معي» (Think-Along)\n\n🎮 نظام التقدم:\nXP لكل مفهوم واختبار\nسلسلة يومية 🔥\nشاشة إنجاز + شارات\n\n💰 نظام البيع (Freemium):\nمرحلتان مجانيتان + 4 مدفوعة بـ $19\nبوابة وصول SHA-256\nرمز: CHESSMIND2026\n\n🌍 الروابط:\nعربي: /app.html\nإنجليزي: /en.html\nصفحة هبوط EN: /en/\n\n🚀 النشر:\nGitHub Pages",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "GitHub Pages",
      "Gumroad",
      "AR+EN",
      "Quizzes",
      "XP System",
    ],
    path: "github:aneerabee/chess-academy",
    links: {
      العربي: "https://aneerabee.github.io/chess-academy/",
      English: "https://aneerabee.github.io/chess-academy/en.html",
      GitHub: "https://github.com/aneerabee/chess-academy",
    },
  },
  {
    name: "Western Office",
    id: "western-office",
    kind: "internal-tool",
    ar: "نظام مكتب الحوالات",
    st: "a",
    em: "💸",
    cl: "#0f766e",
    pct: 88,
    summary:
      "نظام تشغيل داخلي لمكتب حوالات ويسترن — يدير الزبائن والحوالات والتسويات والإقفال اليومي والأرباح، مع رابط مشاهدة محصور لكل زبون تجاري.",
    local_path:
      "/Users/rabeeshaban/Documents/New project/western-office",
    server_path: null,
    repo_url: "https://github.com/aneerabee/western-office",
    deploy_url: "https://aneerabee.github.io/western-office/",
    stack: [
      "React 19",
      "Vite 8",
      "Vitest",
      "Supabase",
      "GitHub Pages",
      "GitHub Actions",
    ],
    subsystems: [
      "transfer-lifecycle",
      "customer-ledger",
      "settlement-engine",
      "settlement-history",
      "daily-closing",
      "profit-claim",
      "senders-receivers-registry",
      "dual-persistence",
      "rolling-snapshots",
      "undo-queue",
      "history-audit",
      "viewer-mode",
    ],
    related_services: [],
    related_tools: ["Claude Code"],
    related_cloud: ["GitHub", "Supabase"],
    ops: [
      "نشر تلقائي على GitHub Pages عبر GitHub Actions عند كل دفعة على main",
      "تخزين مزدوج: Supabase (wo_* tables) + localStorage mirror كشبكة أمان",
      "مصدر حقيقة موحّد: قاعدة بيانات Supabase واحدة للإدارة ولروابط المشاهدة",
      "203 اختبار Vitest (8 ملفات) — كل شيء أخضر قبل أي دفعة",
      "نسخة احتياطية تلقائية يومية تُنزّل JSON إلى جهاز المستخدم",
      "5 لقطات دوّارة في localStorage (واحدة كل ساعة) كشبكة أمان إضافية",
      "حماية متعدّدة التبويبات عبر BroadcastChannel — التبويب الأقدم يصبح للقراءة فقط",
      "زر تراجع لمدّة دقيقتين بعد أي عملية مدمّرة للبيانات",
      "تحديث تلقائي لرابط الزبون كل 15 ثانية + عند عودة التبويب للنشاط",
    ],
    desc: "نظام تشغيل يومي لمكتب حوالات ويسترن بإدارة يد واحدة\n\n🔄 دورة الحوالة:\nوصلت → عند الموظف → مراجعة لاحقة / تم السحب / مشكلة\nتحقق ذكي: لا إرسال بدون مبالغ، لا سحب بدون مستلم\nنموذج إضافة مفرد أو دفعة متعدّدة لنفس الزبون\n\n💰 النظام المالي:\nمبلغ الحوالة (معلوماتي) + للزبون + المستلم من الموظف = الربح\nدفتر حسابات ledger حقيقي لكل زبون\nكشف حساب بأرصدة تراكمية\nتسوية: المحاسب يسلّم → المكتب يدفع للزبون → الربح يبقى\nمطالبة الأرباح (Claim) مع سجل زمني كامل\nبانر أخضر بارز فوق كل تبويب عند وجود ربح قابل للسحب\n\n📊 التبويبات (7):\nالحوالات — بطاقات مرتّبة بالأولوية الذكية + نموذج تعديل + سجل تاريخي لكل حوالة\nالزبائن — حوالات كل زبون + كشف حساب تراكمي + تسوية فردية\nالأشخاص — سجلّ عالمي للمرسلين والمستلمين بتلوين ذكي حسب التكرار\nالتسويات — عرض المعلّق + سجل تاريخي كامل قابل للبحث والتصفية\nالإقفال اليومي — 3 مستويات (زبائن تراكمي + مكتب يومي + محاسب تراكمي) + تقارير سابقة\nالمشاكل — تجميع حسب النوع + حلّ سريع\nالمحذوفات — استرجاع ناعم للحوالات والزبائن المحذوفين\n\n👁️ وضع المشاهدة للزبون التجاري:\nرابط خاص `?viewer=<customerId>` يعطي الزبون نافذة آمنة على بياناته هو فقط\nيرى: حوالاته، تسوياته، شريط ملخّص مالي (مستحق له + استلمت سابقاً)\nلا يرى: ربحك، كاش المحاسب، أي زبون آخر، أي نموذج إدارة\nالمرسلون/المستلمون بأعدادهم الحقيقية العالمية (بدون كشف لمن يخصّون)\nتحديث تلقائي حيّ كل 15 ثانية بدون إعادة تحميل\nكل معالجات التعديل محميّة بصرامة (blockIfReadOnly على 15 handler)\n\n🛡️ الحماية والاسترجاع:\nحذف ناعم (soft delete) لكل شيء — الأصل محفوظ للاسترجاع\nزر تراجع لدقيقتين بعد عمليات الإعادة التي تمسح البيانات\nتنبيه غنيّ قبل الإعادة: رقم الحوالة + الزبون + قائمة بكل ما سيُحذف\nسجل تاريخي (history) على كل حوالة بآخر 50 تغيير\n5 لقطات دوّارة في localStorage + نسخة احتياطية يومية تلقائية\nحماية مزدوجة التبويبات — الأحدث يسيطر والأقدم للقراءة\nكشف فشل localStorage ببانر أحمر فوري\n\n🗄️ التخزين:\nSupabase (wo_customers, wo_transfers, wo_ledger_entries, wo_claim_history, wo_daily_closings, wo_senders, wo_receivers) — JSONB\nlocalStorage v3 كشبكة أمان أوفلاين\nهجرة تلقائية من الصيغ القديمة (v2, v1)\nاستيراد/تصدير JSON كامل\nmergeLoadResults يحمي من مسح المرسلين/المستلمين إذا فقدت جداولهم مؤقتاً\n\n🧪 الجودة:\n203 اختبار Vitest في 8 ملفات:\n- transferLogic (70) — المنطق الأساسي\n- people (35) — سجلّ المرسلين/المستلمين\n- viewerMode (24) — التصفية والصلاحيات\n- settlementHistory (20) — سجلّ التسويات\n- snapshots (14) — اللقطات الدوّارة\n- profitClaim (11) — المطالبة بالربح + التوازن المحاسبي\n- dailyClosing (11) — الإقفال اليومي\n- dataIntegrity (10) — الهجرة والسلامة\n- persistence (8) — التخزين المزدوج\nبناء Vite نظيف — 530KB / 143KB gzip\n\n🛣️ خارطة التطوير:\n✅ نموذج بيانات + ledger + تسويات + إقفال يومي + مطالبة أرباح\n✅ سجل تسويات كامل مع فلترة وبحث\n✅ Supabase سحابي كامل مع جداول منفصلة\n✅ وضع مشاهدة صارم لكل زبون عبر رابط خاص\n✅ لقطات دوّارة + نسخة احتياطية يومية + زر تراجع\n✅ سجل تاريخي بصري لكل حوالة\n✅ بانر ربح قابل للسحب مرئي في كل التبويبات\n⏳ ربط Telegram Bot (إشعارات الحوالات الجديدة)\n⏳ تقارير PDF شهرية وسنوية\n⏳ RLS سياسات على مستوى قاعدة البيانات لحماية أقوى\n⏳ استبدال رمز $ بـ₺ (ليرة تركية)",
    tags: [
      "React 19",
      "Vite 8",
      "Vitest 192+11",
      "Supabase JSONB",
      "Ledger",
      "RTL Arabic",
      "Viewer Mode",
      "Soft Delete",
      "Undo Queue",
      "Rolling Snapshots",
      "GitHub Pages",
    ],
    path: "/Users/rabeeshaban/Documents/New project/western-office",
    links: {
      التطبيق: "https://aneerabee.github.io/western-office/",
      "مشاهدة مثال": "https://aneerabee.github.io/western-office/?viewer=1776004308716001",
      GitHub: "https://github.com/aneerabee/western-office",
      Supabase: "https://supabase.com/dashboard/project/fiancnwrfehyrkvfjwfq",
    },
  },
  {
    name: "Mohammad Ledger",
    id: "mohammad-ledger",
    kind: "financial-ledger",
    ar: "دفتر محمد",
    st: "a",
    em: "📒",
    cl: "#16A34A",
    pct: 62,
    summary:
      "دفتر مالي شخصي/تشغيلي لمحمد مبني من ملف Numbers قديم، مع أرصدة أشخاص وحسابات كاش/مصرفي وأصول ومصروفات، وتجهيز بوت Telegram للإدخال والمراجعة.",
    local_path:
      "/Users/rabeeshaban/Documents/New project/western-office",
    server_path: null,
    repo_url: "https://github.com/aneerabee/mohammad-ledger",
    deploy_url: "https://aneerabee.github.io/mohammad-ledger/",
    stack: [
      "React 19",
      "Vite 8",
      "Supabase",
      "Telegram Bot API",
      "Node.js",
      "GitHub Pages",
      "Vitest",
    ],
    subsystems: [
      "ledger-core",
      "account-catalog",
      "movement-entry-wizard",
      "balance-review",
      "history-audit",
      "supabase-state",
      "local-safety-backups",
      "telegram-bot-foundation",
      "idempotent-telegram-posting",
    ],
    related_services: [],
    related_tools: ["Claude Code"],
    related_cloud: ["GitHub", "Supabase", "Telegram"],
    ops: [
      "الواجهة منشورة على GitHub Pages كرابط مستقل لمحمد",
      "مصدر البيانات الحالي: صف واحد في Supabase ml_state مع mirror محلي ونسخ محلية تلقائية",
      "الحركات تمر عبر ledgerCore: validateMovement + previewMovement + postMovement",
      "Telegram Bot في مرحلة الأساس: خدمة مشتركة + repository آمن + منع تكرار التأكيد",
      "اختبارات المرحلة الأولى: 17 اختبارًا تمر، وبناء Vite ناجح",
    ],
    desc: "دفتر محمد — منظومة مالية مبنية بعناية من منظومة Numbers قديمة\n\n🎯 الهدف:\nصديق لا يعرف استخدام الكمبيوتر يحتاج طريقة سهلة جدًا لإدخال ومراجعة حركاته المالية من الهاتف، مع واجهة ويب وبوت Telegram لاحقًا.\n\n💰 نطاق الدفتر:\nأشخاص وجهات: أقبض منهم / أدفع لهم\nأماكن المال: كاش ومصرفي منفصلان لأن قيمتهما قد تختلف\nأصول: شاحنة، أرض، ألعاب، أشياء لها قيمة\nمصروف: مصروف شخصي وتكاليف نهائية\nمراجعة: حسابات أو حركات غير مؤكدة لا تؤثر حتى تُحل\n\n🔄 أنواع الحركات:\nتحويل من حساب إلى حساب\nمصروف من طرف واحد\nبيع دولار: دولار يخرج ودينار يدخل بسعر صرف\nشراء دولار: دينار يخرج ودولار يدخل بسعر صرف\nتصحيح ورصيد افتتاحي وحركات مراجعة عند الحاجة\n\n🧠 المنطق:\nكل حركة تعرض تأثيرها قبل الحفظ\nلا حفظ لحركة ناقصة كحركة مؤثرة\nلا تحويل من نفس الحساب لنفس الحساب\nلا تحويل بين نفس الاسم ونفس التفصيل\nإلغاء/تعديل مباشر للحركات الحديثة فقط، والقديم يتم عبر تصحيح\nالأرقام تظهر بفواصل آلاف وبدون كسور إلا أسعار الصرف\n\n📱 الواجهة:\nمصممة للهاتف أولًا\nإدخال الحركة كخطوات متتابعة وليس نموذجًا مزدحمًا\nالأرصدة مقسمة: مالي، أقبض منهم، أدفع لهم، صفر، أصول، مصروف، مراجعة\nكل حساب يفتح ملخصه وحركاته وتعديل تصنيفه\n\n🤖 Telegram Bot:\nبدأت المرحلة الأولى: خدمة مشتركة على السيرفر تستخدم نفس ledgerCore\nRepository آمن يقرأ/يحفظ ml_state مع حماية من تضارب الكتابة\nجلسات إدخال مؤقتة في Telegram\nتأكيد نهائي قبل الحفظ\nمنع تكرار الحفظ عند ضغط زر التأكيد مرتين عبر idempotencyKey\n\n🛡️ الأمان وحفظ البيانات:\nSupabase هو المصدر السحابي\nlocalStorage mirror ونسخ محلية تلقائية كشبكة أمان\nالبوت لن يعمل إلا لمستخدم Telegram مسموح\nمفتاح Supabase service role يجب أن يبقى في السيرفر فقط وليس GitHub Pages",
    tags: [
      "React 19",
      "Vite 8",
      "Supabase",
      "Telegram Bot",
      "Ledger",
      "RTL Arabic",
      "Financial Workflow",
      "GitHub Pages",
      "Idempotency",
    ],
    path: "/Users/rabeeshaban/Documents/New project/western-office",
    links: {
      التطبيق: "https://aneerabee.github.io/mohammad-ledger/",
      GitHub: "https://github.com/aneerabee/mohammad-ledger",
      Supabase: "https://supabase.com/dashboard/project/fiancnwrfehyrkvfjwfq",
      Telegram: "https://core.telegram.org/bots",
    },
    links_desc: {
      التطبيق: "الرابط الحي الذي يستخدمه محمد من الهاتف والكمبيوتر",
      GitHub: "مستودع النشر الخاص بدفتر محمد على GitHub Pages",
      Supabase: "قاعدة البيانات السحابية التي تحتوي ml_state ومصدر الحقيقة الحالي",
      Telegram: "مرجع Telegram Bot API المستخدم لبناء تجربة الإدخال والمراجعة",
    },
    current_status: {
      updated: "2026-05-09",
      where:
        "الواجهة الحية منشورة ومثبتة على رابط مستقل. منطق الدفتر والأرصدة والحركات يعمل عبر ledgerCore وSupabase. بدأت مرحلة Telegram Bot بأساس تقني مشترك: repository آمن، service للبوت، wizard للحركة، ومنع تكرار التأكيد.",
      next_step:
        "ضبط TELEGRAM_BOT_TOKEN وMOHAMMAD_TELEGRAM_USER_ID وSUPABASE_SERVICE_ROLE_KEY في بيئة سيرفر آمنة، ثم اختبار أول حركة من Telegram وظهورها في الموقع.",
      blockers: [
        {
          text: "لم يتم ضبط توكن Telegram والـ user id المسموح بعد",
          priority: "high",
        },
        {
          text: "يجب اختيار مكان تشغيل دائم للبوت: Railway أو VPS أو Render",
          priority: "high",
        },
        {
          text: "الحفظ الحالي ما زال في صف ml_state واحد؛ مناسب للمرحلة الأولى لكن يحتاج مراقبة عند تشغيل الموقع والبوت معًا",
          priority: "med",
        },
        {
          text: "قسم المراجعة الكامل من Telegram لم يُبن بعد؛ المرحلة الأولى تركز على إدخال الحركة والحفظ الآمن",
          priority: "med",
        },
      ],
      use_guide:
        "للاستخدام اليومي: افتح رابط التطبيق لمراجعة الأرصدة والسجل. للتطوير: افتح المشروع المحلي وشغّل اختبارات ledger قبل أي تعديل. للبوت: لا تشغّل إلا بمتغيرات بيئة آمنة، ولا تضع service role في الواجهة أو GitHub Pages.",
    },
    claude_session: {
      session_name: "[mohammad ledger telegram bot]",
      terminal: "Codex / Core Shell",
      cwd: "/Users/rabeeshaban/Documents/New project/western-office",
      command:
        "cd /Users/rabeeshaban/Documents/New\\ project/western-office && claude",
      note: "آخر نقطة: المرحلة الأولى للبوت أُنشئت محليًا — shared ledger state + server repository + telegram movement wizard + idempotency، مع 17 اختبارًا ناجحًا وبناء Vite ناجح.",
    },
  },
];

const SVC = [
  {
    name: "Wapy App",
    id: "wapy-app",
    st: 1,
    em: "💳",
    host: "Contabo VPS",
    runtime: "Docker / Next.js",
    service_type: "container",
    prj: "Wapy.dev",
    owner: "Wapy.dev",
    owner_type: "project",
    path: "server:/opt/wapy",
    port: "3000",
    schedule: "دائم",
    dt: "wapydev-app · Docker container",
    info: "واجهة Wapy.dev الحية عبر Tailscale",
  },
  {
    name: "Wapy Cron",
    id: "wapy-cron",
    st: 1,
    em: "⏰",
    host: "Contabo VPS",
    runtime: "Docker / Alpine",
    service_type: "container",
    prj: "Wapy.dev",
    owner: "Wapy.dev",
    owner_type: "project",
    path: "server:/opt/wapy",
    port: "—",
    schedule: "دائم",
    dt: "wapydev-cron · Docker container",
    info: "حاوية cron خاصة بمهام Wapy.dev المجدولة",
  },
  {
    name: "Wapy DB",
    id: "wapy-db",
    st: 1,
    em: "🗄️",
    host: "Contabo VPS",
    runtime: "PostgreSQL 17.5",
    service_type: "database",
    prj: "Wapy.dev",
    owner: "Wapy.dev",
    owner_type: "project",
    path: "server:/opt/wapy/db",
    port: "5432",
    schedule: "دائم",
    dt: "wapydev-db · PostgreSQL 17.5",
    info: "قاعدة بيانات Wapy.dev مربوطة محليًا على 127.0.0.1",
  },
  {
    name: "Argaz Gateway",
    id: "argaz-gateway",
    st: 1,
    em: "🤖",
    host: "Contabo VPS",
    runtime: "OpenClaw 2026.2.6-3",
    service_type: "agent-runtime",
    prj: "",
    owner: "Argaz Bot",
    owner_type: "bot",
    path: "server:/home/argaz/.openclaw",
    port: "18789",
    schedule: "دائم",
    dt: "OpenClaw gateway + model chain",
    info: "الـ runtime الرئيسي لـ Argaz والوكلاء المعزولين",
  },
  {
    name: "Chrome Headless",
    id: "chrome-headless",
    st: 1,
    em: "🌐",
    host: "Contabo VPS",
    runtime: "systemd user service",
    service_type: "user-service",
    prj: "EasyBooking",
    owner: "EasyBooking",
    owner_type: "project",
    path: "server:/home/argaz/.config/systemd/user/chrome-headless.service",
    port: "—",
    schedule: "دائم",
    dt: "Browser automation · systemd",
    info: "متصفح بدون واجهة يستخدمه OpenClaw والعمليات المؤتمتة",
  },
  {
    name: "Wapy Backup",
    id: "wapy-backup-cron",
    st: 1,
    em: "💾",
    host: "Contabo VPS",
    runtime: "cron",
    service_type: "cron",
    prj: "Wapy.dev",
    owner: "Wapy.dev",
    owner_type: "project",
    path: "server:/opt/wapy/scripts/backup.sh",
    port: "—",
    schedule: "يوميًا 3 صباحًا",
    dt: "0 3 * * *",
    info: "pg/sql backup محفوظ داخل ‎.backup",
  },
  {
    name: "Wapy Cleanup",
    id: "wapy-cleanup-cron",
    st: 1,
    em: "🧹",
    host: "Contabo VPS",
    runtime: "cron",
    service_type: "cron",
    prj: "Wapy.dev",
    owner: "Wapy.dev",
    owner_type: "project",
    path: "server:/opt/wapy/.backup",
    port: "—",
    schedule: "يوميًا 4 صباحًا",
    dt: "0 4 * * *",
    info: "حذف نسخ Wapy.dev الأقدم من 30 يومًا",
  },
  {
    name: "Gateway Watchdog",
    id: "gateway-watchdog",
    st: 1,
    em: "🛡️",
    host: "Contabo VPS",
    runtime: "cron",
    service_type: "cron",
    prj: "",
    owner: "Argaz Bot",
    owner_type: "bot",
    path: "server:/home/argaz/gateway-watchdog.sh",
    port: "—",
    schedule: "كل دقيقة",
    dt: "* * * * *",
    info: "يراقب OpenClaw ويعيد التشغيل عند التوقف",
  },
  {
    name: "Config Backup",
    id: "config-backup",
    st: 1,
    em: "🗂️",
    host: "Contabo VPS",
    runtime: "cron",
    service_type: "cron",
    prj: "",
    owner: "Argaz Bot",
    owner_type: "bot",
    path: "server:/home/argaz/backup-config.sh",
    port: "—",
    schedule: "كل ساعة",
    dt: "0 * * * *",
    info: "يحفظ نسخًا من openclaw.json عند التغيير",
  },
  {
    name: "OpenClaw Gateway Service",
    id: "openclaw-gateway-service",
    st: 1,
    em: "🔌",
    host: "Contabo VPS",
    runtime: "systemd user service",
    service_type: "user-service",
    prj: "",
    owner: "Argaz Bot",
    owner_type: "bot",
    path: "server:/home/argaz/.config/systemd/user/openclaw-gateway.service",
    port: "18789",
    schedule: "دائم",
    dt: "openclaw-gateway.service · systemd user unit",
    info: "وحدة systemd الفعلية التي تحمل gateway على السيرفر؛ صحة runtime التفصيلية تُراجع أيضًا عبر Argaz Gateway",
  },
  {
    name: "Tailscale VPN",
    id: "tailscale-vpn",
    st: 1,
    em: "🔒",
    host: "متعدد",
    runtime: "VPN mesh",
    service_type: "network",
    prj: "Command Center",
    owner: "Command Center",
    owner_type: "project",
    path: "100.116.69.101",
    port: "—",
    schedule: "دائم",
    dt: "MacBook + iPhone + Server",
    info: "شبكة VPN خاصة للوصول الآمن إلى الخدمات الداخلية",
  },
];

const AUTO = [
  {
    group: "MacBook Pro",
    loc: "launchd / محلي",
    host: "desktop",
    tasks: [
      {
        name: "auto-backup.sh",
        freq: "يوميًا 14:00",
        on: true,
        what: "دفع meta-mcp + Money Manager + brixtravelwebsite إلى GitHub",
        prj: ["Meta MCP", "Money Manager", "BRIX Travel Website"],
        path: "local launchd",
        kind: "backup",
      },
      {
        name: "Command Center Runtime Publish",
        freq: "كل 6 ساعات",
        on: true,
        what: "تشغيل runtime-sync.js ثم commit/push لـ data.runtime.json عند التغيير",
        prj: ["Command Center"],
        path: "/Users/rabeeshaban/Library/LaunchAgents/com.rabeeshaban.command-center-runtime-publish.plist",
        kind: "automation",
      },
      {
        name: "PM2 Resurrect",
        freq: "عند الإقلاع",
        on: true,
        what: "إعادة تشغيل العمليات المحلية المحفوظة تلقائيًا",
        prj: ["Command Center"],
        path: "local pm2",
        kind: "runtime",
      },
      {
        name: "BRIX Invoice Server",
        freq: "دائم",
        on: true,
        what: "تشغيل خادم فواتير BRIX محليًا",
        prj: ["BRIX Travel System"],
        path: "localhost:8000",
        kind: "app",
      },
    ],
  },
  {
    group: "Contabo VPS",
    loc: "cron + systemd",
    host: "server",
    tasks: [
      {
        name: "Wapy.dev DB Dump",
        freq: "يوميًا 3 صباحًا",
        on: true,
        what: "تنفيذ backup لبيانات Wapy.dev",
        prj: ["Wapy.dev"],
        path: "server:/opt/wapy/scripts/backup.sh",
        kind: "backup",
      },
      {
        name: "Wapy.dev Cleanup",
        freq: "يوميًا 4 صباحًا",
        on: true,
        what: "تنظيف النسخ القديمة الأقدم من 30 يومًا",
        prj: ["Wapy.dev"],
        path: "server:/opt/wapy/.backup",
        kind: "cleanup",
      },
      {
        name: "Argaz Config Backup",
        freq: "كل ساعة",
        on: true,
        what: "حفظ نسخ openclaw.json عند التغييرات",
        prj: ["Argaz Bot"],
        path: "server:/home/argaz/backup-config.sh",
        kind: "backup",
      },
      {
        name: "Gateway Watchdog",
        freq: "كل دقيقة",
        on: true,
        what: "مراقبة gateway وإعادة تشغيله عند التوقف",
        prj: ["Argaz Bot"],
        path: "server:/home/argaz/gateway-watchdog.sh",
        kind: "watchdog",
      },
    ],
  },
  {
    group: "Argaz Bot",
    loc: "OpenClaw Scheduler",
    host: "server",
    tasks: [
      {
        name: "Morning Briefing",
        freq: "08:00 يوميًا",
        on: true,
        what: "Gmail + طقس أنطاليا + ذاكرة → Telegram",
        prj: ["Argaz Bot"],
        path: "server:/home/argaz/.openclaw/workspace",
        kind: "briefing",
      },
      {
        name: "Daily Self-Review",
        freq: "كل 24 ساعة",
        on: true,
        what: "مراجعة التعلمات وتحديث الذاكرة",
        prj: ["Argaz Bot"],
        path: "server:/home/argaz/.openclaw/workspace/MEMORY.md",
        kind: "memory",
      },
      {
        name: "Memory Maintenance",
        freq: "03:00 كل يومين",
        on: false,
        what: "تنظيف وصيانة ملفات الذاكرة",
        prj: ["Argaz Bot"],
        path: "server:/home/argaz/.openclaw/memory",
        kind: "maintenance",
      },
      {
        name: "Weekly Skill Extraction",
        freq: "أسبوعيًا",
        on: false,
        what: "استخراج مهارات جديدة من التعلمات",
        prj: ["Argaz Bot"],
        path: "server:/home/argaz/.openclaw/workspace/.learnings",
        kind: "learning",
      },
      {
        name: "Error Pattern Detection",
        freq: "كل 3 أيام",
        on: false,
        what: "كشف الأنماط المتكررة في الأخطاء",
        prj: ["Argaz Bot"],
        path: "server:/home/argaz/.openclaw/workspace/.learnings/ERRORS.md",
        kind: "diagnostics",
      },
    ],
  },
  {
    group: "Claude Code",
    loc: "Hooks",
    host: "desktop",
    tasks: [
      {
        name: "PreToolUse",
        freq: "3 hooks",
        on: true,
        what: "تحقق قبل الأدوات وقيود العمل",
        prj: ["Command Center"],
        path: "/Users/rabeeshaban/.claude",
        kind: "hook",
      },
      {
        name: "PostToolUse",
        freq: "2 hooks",
        on: true,
        what: "تنسيق وفحص بعد الأدوات",
        prj: ["Command Center"],
        path: "/Users/rabeeshaban/.claude",
        kind: "hook",
      },
      {
        name: "Stop",
        freq: "1 hook",
        on: true,
        what: "تحقق نهائي قبل إنهاء الجلسة",
        prj: ["Command Center"],
        path: "/Users/rabeeshaban/.claude",
        kind: "hook",
      },
    ],
  },
];

const BOT = [
  {
    name: "Tron Address Bot",
    id: "tron-address-bot",
    kind: "telegram-bot",
    ar: "بوت عناوين ترون",
    st: "a",
    em: "⚡",
    cl: "#10B981",
    host: "محلي",
    runtime: "Node.js",
    channel: "Telegram",
    related_entities: ["Vault"],
    summary: "بوت حساس أمنيًا لإدارة محافظ Tron ومراقبة العناوين.",
    desc: "بوت Telegram لمراقبة عناوين ترون وإدارة المحافظ\n\n⚡ وضع التشغيل: عند الطلب فقط\nيُشغَّل يدوياً لوقت محدود ثم يُغلق\nالسبب: حساسية البيانات (محافظ + مفاتيح)\n\n🔐 الأمان:\nتشفير AES-256 + كلمة مرور رئيسية\nحد 5 محاولات + قفل 15 دقيقة\nملفات حساسة محمية (600)\n\n🛡️ تدقيق أمني مارس 2026:\n26 ثغرة اكتُشفت وأُصلحت\nتحديث كل المكتبات\nمقارنة كلمة مرور آمنة ضد timing attacks\n\n🚀 التشغيل:\nstart-bot-background.sh",
    tags: ["Node.js", "TronWeb", "AES-256", "On-Demand"],
    path: "/Users/rabeeshaban/Desktop/Projects/🤖 Bots/🕵️ tron-address-bot",
  },
  {
    name: "Bank Bot",
    id: "bank-bot",
    kind: "telegram-bot",
    ar: "بوت كشوف البنك",
    st: "p",
    em: "🏦",
    cl: "#2563EB",
    host: "سحابي",
    runtime: "Python",
    channel: "Telegram",
    related_entities: ["Heroku"],
    summary: "بوت OCR لتحليل كشوف البنك، متوقف حاليًا.",
    desc: "بوت Telegram لتحليل كشوف البنك تلقائياً\n\n📸 كيف يعمل:\nأرسل صورة كشف الحساب\nيستخرج البيانات بتقنية OCR\nيحلل التحويلات والأرصدة\n\n📊 التصدير:\nCSV + Excel\nتقارير مفصلة\n\n🔧 التقنيات:\nPython + pytesseract + pandas\nمنشور على Heroku (متوقف حالياً)",
    tags: ["Python", "OCR", "Heroku", "pandas"],
    path: "/Users/rabeeshaban/Desktop/Archive/bank-bot",
    links: { Heroku: "https://dashboard.heroku.com/apps/ruble-transfer-bot" },
  },
  {
    name: "Argaz Bot",
    id: "argaz-bot",
    kind: "agent-runtime",
    ar: "بوت أرقاز",
    st: "a",
    em: "🧠",
    cl: "#6C3AED",
    host: "Contabo VPS",
    runtime: "OpenClaw 2026.2.6-3",
    channel: "Telegram @Argaz_clawbot",
    related_entities: ["Lobster", "Command Center"],
    summary:
      "runtime متعدد الوكلاء مع gateway وmemory وscheduler، وليس بوتًا بسيطًا.",
    desc: "بوت ذكاء اصطناعي شخصي — OpenClaw 2026.2.6-3\n\n🤖 Telegram: @Argaz_clawbot\nالسيرفر: Contabo · منفذ 18789\nساعات الهدوء: 23:00 – 07:30\n\n🧠 النماذج (بالترتيب):\n1. Gemini 2.5 Flash — الأساسي\n2. LLaMA 3.3-70B (Groq) — الاحتياطي الأول\n3. LLaMA 3.1-8B (Groq) — سريع\n4. Kimi-K2.5 (Moonshot)\n5. Kimi-K2-turbo-preview\n6. MiniMax-M2.1\n\n👥 3 وكلاء مستقلين:\nmain (Argaz) — نشط 24/7\nwork (عامل) — مُعدّ للعمل\nbrix-travel (بريكس) — مُعدّ\n\n🛠️ 13 مهارة:\ncode-generator · reminders-tasks · multi-agent\nclaude-usage · research · memory-manager\nreflect-learn · preprompt · self-improving\nvoice · character + 2 داخلية\n\n⏰ التاسكات السحابية (OpenClaw Cron):\n08:00 يومياً ← morning-briefing\nGmail + طقس أنطاليا + ذاكرة → Telegram\nكل 24 ساعة ← daily-self-review\nمراجعة learnings + تحديث الذاكرة\n03:00 كل يومين ← memory-maintenance\nتنظيف وصيانة ملفات الذاكرة\nأسبوعياً ← weekly-skill-extraction\nاستخراج مهارات جديدة من التعلمات\nكل 3 أيام ← error-pattern-detection\nكشف أنماط الأخطاء المتكررة\n🛡️ حماية النظام (System Cron):\nكل دقيقة ← gateway-watchdog\nمراقبة OpenClaw وإعادة تشغيله تلقائياً\nكل ساعة ← backup-config\nنسخ احتياطي لـ openclaw.json عند التغيير",
    tags: [
      "Gemini",
      "AI",
      "24/7",
      "OpenClaw",
      "13 Skills",
      "6 Models",
      "5 Cron Jobs",
    ],
    path: "server:/home/argaz/.openclaw",
  },
  {
    name: "Claude Code Bot",
    id: "claude-code-bot",
    kind: "assistant-channel",
    ar: "بوت كلاود كود",
    st: "a",
    em: "⚡",
    cl: "#8B5CF6",
    host: "MacBook",
    runtime: "Claude Code + plugin",
    channel: "Telegram",
    related_entities: ["Command Center"],
    summary: "قناة تحكم عن بُعد بـ Claude Code عبر Telegram.",
    desc: "بوت Telegram للتحكم بـ Claude Code عن بُعد\n\nPlugin: telegram@claude-plugins-official v0.0.4\nMCP Server — grammy + Bun\n\n📍 الموقع:\n/Users/rabeeshaban/.claude/channels/telegram\n\n🔐 الوصول:\nPolicy: allowlist — مغلق للغرباء\nمسموح: ID واحد فقط (أنت)\nلا تاريخ رسائل · لا بحث\n\n🛠️ أدوات البوت:\nreply — إرسال ردود + مرفقات حتى 50MB\nreact — إيموجي ريأكشن على رسائلك\nedit_message — تعديل رسائل البوت (progress)\n\n📸 الصور الواردة:\nتُحفظ تلقائياً في inbox/ وتُقرأ مباشرة\n\n🚀 التشغيل:\nclaude --channels plugin:telegram@claude-plugins-official\n\n⚠️ لا تاسكات مجدولة — يرد فقط عند مراسلتك",
    tags: [
      "MCP Server",
      "grammy",
      "Bun",
      "Telegram",
      "Claude Code",
      "allowlist",
    ],
    path: "/Users/rabeeshaban/.claude/channels/telegram",
  },
  {
    name: "Mohammad Ledger Bot",
    id: "mohammad-ledger-bot",
    kind: "telegram-bot",
    ar: "بوت دفتر محمد",
    st: "p",
    em: "📒",
    cl: "#16A34A",
    host: "غير محدد بعد",
    runtime: "Node.js",
    channel: "Telegram",
    related_entities: ["Mohammad Ledger", "Supabase", "GitHub"],
    summary:
      "بوت Telegram لإدخال حركات دفتر محمد ومراجعة الحسابات والسجل من الهاتف، مبني فوق نفس منطق ledgerCore.",
    desc: "بوت دفتر محمد — مرحلة الأساس\n\n🎯 الهدف:\nجعل محمد يدخل الحركات ويراجع الأرصدة والسجل من Telegram بدون فتح الكمبيوتر.\n\n✅ المنجز:\nهيكل بوت Node.js\nحماية allowlist عبر Telegram user id\nجلسات إدخال مؤقتة\nWizard للحركة: نوع → مبلغ → عملة/سعر → مصدر → وجهة → ملاحظة → مراجعة → تأكيد\nمعاينة التأثير قبل الحفظ\nالحفظ عبر نفس ledgerCore المستخدم في الموقع\nمنع تكرار الحركة عند ضغط التأكيد مرتين عبر idempotencyKey\nRepository آمن يقرأ ويحفظ ml_state في Supabase\n\n⏳ التالي:\nتشغيل بتوكن حقيقي في بيئة آمنة\nاختبار أول حركة من Telegram وظهورها في الموقع\nإضافة الحسابات والبحث والسجل والمراجعة الكاملة\nاختيار استضافة دائمة للبوت\n\n🔐 شروط الأمان:\nTELEGRAM_BOT_TOKEN وSUPABASE_SERVICE_ROLE_KEY في السيرفر فقط\nالبوت مغلق على user id محدد\nلا حفظ بدون تأكيد نهائي\nلا استخدام لحسابات مخفية أو ملخصات",
    tags: [
      "Telegram",
      "Node.js",
      "Supabase",
      "Ledger",
      "Idempotency",
      "Allowlist",
      "Arabic UX",
    ],
    path: "/Users/rabeeshaban/Documents/New project/western-office/server/telegram/bot.js",
    related_projects: ["Mohammad Ledger"],
    links: {
      GitHub: "https://github.com/aneerabee/mohammad-ledger",
      "Telegram Bot API": "https://core.telegram.org/bots",
    },
  },
];

const TL = [
  {
    name: "Codex CLI",
    id: "codex-cli",
    ar: "إعداد Codex",
    st: "a",
    cl: "#0F766E",
    type: "مستخدمة",
    category: "developer-env",
    used_in: ["Command Center", "BRIX Travel System", "EasyBooking"],
    summary:
      "بيئة GPT-5.4 الحالية مع تعليمات دائمة وPlugins مفعلة للمستودعات والتصميم.",
    desc: "Codex يعمل هنا من ~/.codex\n\nالإعدادات المؤكدة من المصدر:\nmodel = gpt-5.4\nmodel_reasoning_effort = xhigh\npersonality = pragmatic\nPlugins مفعلة: GitHub + Canva\nTrusted workspace: /Users/rabeeshaban/Documents/New project\n\nالتخصيص الأهم:\nAGENTS.md يحمل معيار العمل الدائم الذي يحدد عدم الكسر والتنظيف وعدم الهلوسة قبل أي تنفيذ.",
    tags: [
      "gpt-5.4",
      "xhigh reasoning",
      "GitHub plugin",
      "Canva plugin",
      "AGENTS.md",
    ],
    path: "/Users/rabeeshaban/.codex/",
    config_paths: [
      "/Users/rabeeshaban/.codex/config.toml",
      "/Users/rabeeshaban/.codex/AGENTS.md",
    ],
    facts: [
      "model: gpt-5.4",
      "reasoning: xhigh",
      "personality: pragmatic",
      "plugins: GitHub + Canva",
      "trusted workspace: /Users/rabeeshaban/Documents/New project",
    ],
    customizations: [
      "إضافة معيار العمل الدائم داخل AGENTS.md",
      "اعتماد هذا المشروع كـ trusted workspace في config.toml",
    ],
    structure: [
      "config.toml — النموذج والـ plugins والثقة بالمشاريع",
      "AGENTS.md — التعليمات الدائمة التي نعدلها نحن",
      "plugins/cache/openai-curated — إضافات GitHub وCanva",
      "skills/.system — مهارات النظام الأساسية",
      "logs_1.sqlite + state_5.sqlite — سجلات الحالة والجلسات",
    ],
    capabilities: ["GitHub plugin", "Canva plugin", "system skills (5 حاليًا)"],
    edit_points: [
      "عدّل model / reasoning / personality من config.toml",
      "عدّل قواعد العمل الدائمة من AGENTS.md",
      "لا تعدّل cache أو sqlite يدويًا إلا لسبب تقني واضح",
    ],
    links: {},
  },
  {
    name: "Claude Code",
    id: "claude-code",
    ar: "إعداد Claude Code",
    st: "a",
    cl: "#6C3AED",
    type: "مستخدمة",
    category: "developer-env",
    used_in: ["Command Center", "BRIX Travel System", "EasyBooking"],
    summary:
      "بيئة Claude Code الحالية مع Agents وCommands وHooks وPlugins متصلة فعليًا.",
    desc: "Claude Code يعمل من ~/.claude\n\nالإعدادات المؤكدة من المصدر:\n14 agent files\n44 commands\n46 مهارة محلية في ~/.agents/skills\n3 plugins مفعلة عبر enabledPlugins: coderabbit + swift-lsp + telegram\neffortLevel الحالي: medium\nstatusLine مخصص من ~/.claude/scripts/statusline.sh\n\nالتخصيصات المؤكدة:\n3 قواعد PreToolUse\n2 قواعد PostToolUse\nقاعدة Stop لتشغيل صوت النظام\nتنبيه عند وجود console.log\nHook بعد تعديل JS لتشغيل prettier",
    tags: ["14 Agents", "44 Commands", "46 Local Skills", "3 Plugins", "Hooks"],
    path: "/Users/rabeeshaban/.claude/",
    config_paths: [
      "/Users/rabeeshaban/.claude/settings.json",
      "/Users/rabeeshaban/.claude/settings.local.json",
      "/Users/rabeeshaban/.claude/agents",
      "/Users/rabeeshaban/.claude/commands",
      "/Users/rabeeshaban/.claude/channels",
    ],
    facts: [
      "agents: 14",
      "commands: 44",
      "skills: 46 local skills",
      "plugins: coderabbit + swift-lsp + telegram",
      "effortLevel: medium",
      "statusline: ~/.claude/scripts/statusline.sh",
      "permissions allow list: 23 entries",
    ],
    customizations: [
      "PreToolUse hook يذكر باستخدام tmux للأوامر الطويلة",
      "PreToolUse hook يراجع git push قبل الدفع",
      "PostToolUse hook يشغل prettier على JS/TS",
      "PostToolUse hook ينبه عند console.log",
      "Stop hook يشغل صوت النظام عند نهاية الجلسة",
    ],
    structure: [
      "settings.json — الصلاحيات والـ hooks وenabledPlugins",
      "agents/ — 14 وكيلًا متخصصًا",
      "commands/ — 44 أمرًا جاهزًا",
      "plugins/ — سجل الإضافات المفعلة وبياناتها المحلية",
      "channels/telegram — قناة Telegram لـ Claude Code",
      "projects/ + sessions/ + todos/ — سياق العمل والجلسات والخطط",
    ],
    capabilities: [
      "telegram plugin",
      "coderabbit plugin",
      "swift-lsp plugin",
      "14 agents",
      "44 commands",
    ],
    edit_points: [
      "عدّل الصلاحيات والـ plugins والـ hooks من settings.json",
      "عدّل الاستثناءات المحلية من settings.local.json",
      "أضف/عدّل الوكلاء من agents/ والأوامر من commands/",
      "عدّل قناة Telegram من channels/telegram فقط",
    ],
    links: {},
  },
  {
    name: "Runtime Sync System",
    id: "runtime-sync-system",
    ar: "نظام تحديث اللوحة",
    st: "a",
    cl: "#F59E0B",
    type: "مبنية",
    category: "internal-tool",
    used_in: ["Command Center"],
    summary:
      "نظام محلي على macOS يشغّل فحصًا دوريًا عبر launchd، ثم يحدّث data.runtime.json ويدفعه إلى GitHub عند وجود تغيير فقط.",
    desc: "هذا ليس MCP ولا خدمة سحابية.\nإنه نظام محلي على الماك مكوّن من 3 طبقات:\n\n1) runtime-sync.js\nيفحص projects + services + tools + cloud + bots + archive بدرجات تحقق متفاوتة حسب كل نوع\n\n2) runtime-sync-publish.sh\nيشغّل الفحص ثم commit/push فقط إذا تغيّر data.runtime.json\n\n3) LaunchAgent على macOS\nيشغّل النظام كل 6 ساعات عبر launchd\n\nالمهم:\nالذي يُعرض في اللوحة هو آخر نتيجة محفوظة في data.runtime.json، وليس ضمانًا أن كل عنصر مغطى checker مستقل بنفس الجودة.\n\nالغرض:\nتقليل المعلومات القديمة في اللوحة المنشورة بدون الاعتماد على تشغيل يدوي مستمر.",
    tags: ["launchd", "runtime-sync", "GitHub push", "Command Center"],
    path: "/tmp/cc-push",
    config_paths: [
      "/tmp/cc-push/runtime-sync.js",
      "/tmp/cc-push/runtime-sync-publish.sh",
      "/tmp/cc-push/RUNTIME_SYNC.md",
      "/Users/rabeeshaban/Library/LaunchAgents/com.rabeeshaban.command-center-runtime-publish.plist",
    ],
    facts: [
      "scheduler: launchd",
      "interval: كل 6 ساعات",
      "commit policy: فقط عند التغيير",
      "current coverage: projects + services + tools + cloud + bots + archive",
      "runtime file: data.runtime.json",
    ],
    customizations: [
      "lock directory لمنع التشغيل المتوازي",
      "commit فقط لملف data.runtime.json",
      "RunAtLoad + StartInterval عبر launchd",
      "التغطية تختلف حسب نوع العنصر لا بنفس الدرجة للجميع",
    ],
    structure: [
      "runtime-sync.js — منطق الفحص",
      "runtime-sync-publish.sh — منطق التنفيذ والنشر",
      "data.runtime.json — آخر حالة حية محفوظة",
      "RUNTIME_SYNC.md — التوثيق التشغيلي",
      "LaunchAgent plist — الجدولة",
    ],
    capabilities: [
      "filesystem checks",
      "ssh checks",
      "docker/systemd/cron checks",
      "git remote checks",
      "deploy reachability checks",
    ],
    edit_points: [
      "عدّل منطق الفحص في runtime-sync.js",
      "عدّل سياسة النشر في runtime-sync-publish.sh",
      "عدّل الجدولة من LaunchAgent plist",
      "حدّث التوثيق من RUNTIME_SYNC.md",
    ],
    links: {},
  },
  {
    name: "Meta MCP",
    id: "meta-mcp-tool",
    ar: "خادم MCP للإعلانات",
    st: "a",
    cl: "#2563EB",
    type: "مبنية",
    category: "internal-tool",
    used_in: ["EasyBooking", "WhatsApp CRM"],
    summary: "خادم MCP داخلي للتحكم الكامل بإعلانات Meta",
    desc: "37 أداة في 6 وحدات — بديل مجاني لـ Pipeboard\nPython + httpx + Meta Graph API v22.0\nحساب: act_840190289038740\n\n🔒 محفوظ على GitHub (خاص)",
    tags: ["37 Tools", "MCP", "Python"],
    path: "/Users/rabeeshaban/Developer/meta-mcp",
    links: { GitHub: "https://github.com/aneerabee/meta-mcp" },
  },
  {
    name: "GitHub",
    id: "github-tool",
    ar: "مستودعات GitHub",
    st: "a",
    cl: "#10B981",
    type: "مستخدمة",
    category: "platform",
    used_in: [
      "BRIX Travel System",
      "Meta MCP",
      "Money Manager",
      "BRIX Travel Website",
      "Command Center",
      "WhatsApp CRM",
      "Chess Academy",
    ],
    summary: "المنصة المركزية للمستودعات والنشر والتاريخ",
    desc: "حساب: aneerabee — 7 repos في الكتالوج الحالي، منها 6 مؤكدة محليًا من هذا الجهاز\n\nالكتالوج الحالي:\ncommand-center — لوحة التحكم\nchess-academy — أكاديمية الشطرنج\nbrix-travel-system — نظام الحجز\neasybooking-whatsapp-crm — CRM واتساب\nmoney-manager — إدارة مالية\nmeta-mcp — خادم MCP للإعلانات\nbrixtravel — موقع بريكس",
    tags: ["7 Repos", "Source Control", "Deploy History"],
    links: { GitHub: "https://github.com/aneerabee" },
  },
  {
    name: "Tailscale",
    id: "tailscale-tool",
    ar: "شبكة Tailscale الخاصة",
    st: "a",
    cl: "#00E5FF",
    type: "مستخدمة",
    category: "infra-access",
    used_in: ["Wapy.dev", "Argaz Bot", "Command Center"],
    summary: "شبكة VPN الخاصة للوصول إلى الخدمات الداخلية",
    desc: "شبكة VPN خاصة تربط كل الأجهزة:\nسيرفر Contabo: 100.116.69.101 (نشط)\nMacBook Pro: 100.78.245.115 (نشط)\niPhone 15 Pro Max: 100.97.195.82",
    tags: ["VPN", "3 أجهزة", "مشفر"],
  },
  {
    name: "Notion",
    id: "notion-mcp",
    ar: "Notion متصل",
    st: "a",
    cl: "#FFF",
    type: "مستخدمة",
    category: "mcp",
    used_in: ["Claude Code"],
    summary: "MCP للوصول إلى Notion وإدارة المعرفة والمهام",
    desc: "MCP Server متصل بـ Claude Code\nإدارة مشاريع ومهام",
    tags: ["MCP", "Notion"],
  },
  {
    name: "Perplexity",
    id: "perplexity-mcp",
    ar: "بحث Perplexity",
    st: "a",
    cl: "#20B2AA",
    type: "مستخدمة",
    category: "mcp",
    used_in: ["Claude Code"],
    summary: "MCP للبحث العميق والاستكشاف",
    desc: "MCP Server للبحث العميق\nresearch + reason + deep_research",
    tags: ["MCP", "Search", "AI"],
  },
  {
    name: "Filesystem",
    id: "filesystem-mcp",
    ar: "نظام الملفات",
    st: "a",
    cl: "#8B8B8B",
    type: "مستخدمة",
    category: "mcp",
    used_in: ["Claude Code"],
    summary: "MCP للوصول إلى الملفات محليًا",
    desc: "MCP Server للوصول إلى نظام الملفات\nقراءة وكتابة وبحث في الملفات",
    tags: ["MCP", "Files"],
  },
  {
    name: "Memory",
    id: "memory-mcp",
    ar: "ذاكرة المعرفة",
    st: "a",
    cl: "#FF6B6B",
    type: "مستخدمة",
    category: "mcp",
    used_in: ["Claude Code", "Argaz Bot"],
    summary: "MCP لذاكرة الكيانات والعلاقات",
    desc: "MCP Server — رسم بياني للمعرفة\nكيانات + علاقات + ملاحظات",
    tags: ["MCP", "Knowledge Graph"],
  },
  {
    name: "Sequential Thinking",
    id: "sequential-thinking-mcp",
    ar: "التفكير المتسلسل",
    st: "a",
    cl: "#FFD93D",
    type: "مستخدمة",
    category: "mcp",
    used_in: ["Claude Code"],
    summary: "MCP لتحليل المسائل خطوة بخطوة",
    desc: "MCP Server لسلاسل التفكير المنظمة\nتحليل خطوة بخطوة للمسائل المعقدة",
    tags: ["MCP", "Reasoning"],
  },
  {
    name: "Firecrawl",
    id: "firecrawl-mcp",
    ar: "زحف الويب",
    st: "a",
    cl: "#FF4500",
    type: "مستخدمة",
    category: "mcp",
    used_in: ["Claude Code"],
    summary: "MCP لاستخراج الصفحات والزحف",
    desc: "MCP Server لزحف وكشط صفحات الويب\nبحث + استخراج + خريطة موقع",
    tags: ["MCP", "Web Scraping"],
  },
  {
    name: "Magic",
    id: "magic-mcp",
    ar: "سجل الواجهات",
    st: "a",
    cl: "#E040FB",
    type: "مستخدمة",
    category: "mcp",
    used_in: ["Claude Code", "Command Center"],
    summary: "MCP لأنماط ومكوّنات الواجهة",
    desc: "MCP Server — سجل مكونات UI\nبحث واستعراض أنماط التصميم",
    tags: ["MCP", "UI Registry"],
  },
  {
    name: "Supabase",
    id: "supabase-mcp",
    ar: "إدارة قواعد البيانات",
    st: "a",
    cl: "#3ECF8E",
    type: "مستخدمة",
    category: "mcp",
    used_in: ["BRIX Travel System", "Money Manager"],
    summary: "MCP لإدارة Supabase وقاعدة البيانات",
    desc: "MCP Server لإدارة Supabase\nSQL + migrations + edge functions + branches",
    tags: ["MCP", "Database", "PostgreSQL"],
  },
  {
    name: "Vercel",
    id: "vercel-mcp",
    ar: "إدارة النشر",
    st: "a",
    cl: "#000",
    type: "مستخدمة",
    category: "mcp",
    used_in: ["BRIX Travel System"],
    summary: "MCP لإدارة deployments على Vercel",
    desc: "MCP Server لإدارة نشر التطبيقات على Vercel\nربط مع BRIX Travel System",
    tags: ["MCP", "Deployment"],
  },
  {
    name: "Railway",
    id: "railway-mcp",
    ar: "إدارة النشر",
    st: "a",
    cl: "#0B0D0E",
    type: "مستخدمة",
    category: "mcp",
    used_in: ["WhatsApp CRM"],
    summary: "MCP لإدارة deployments على Railway",
    desc: "MCP Server لإدارة نشر التطبيقات على Railway\nربط مع WhatsApp CRM",
    tags: ["MCP", "Deployment"],
  },
  {
    name: "TestSprite",
    id: "testsprite-mcp",
    ar: "اختبارات آلية",
    st: "a",
    cl: "#4CAF50",
    type: "مستخدمة",
    category: "mcp",
    used_in: ["BRIX Travel System", "Command Center"],
    summary: "MCP لتشغيل وتتبع الاختبارات",
    desc: "MCP Server للاختبارات الآلية\nتشغيل ومراقبة الاختبارات",
    tags: ["MCP", "Testing"],
  },
];

const CLD = [
  {
    nm: "GitHub",
    id: "github",
    em: "🐙",
    category: "platform",
    dt: "7 repos في الكتالوج الحالي · 6 مؤكدة محليًا من هذا الجهاز",
    lk: "https://github.com/aneerabee",
    prj: "Command Center",
    related_entities: [
      "Command Center",
      "BRIX Travel System",
      "Chess Academy",
      "Meta MCP",
      "Money Manager",
      "BRIX Travel Website",
      "WhatsApp CRM",
    ],
    used_in: [
      "Command Center",
      "BRIX Travel System",
      "Chess Academy",
      "Meta MCP",
      "Money Manager",
      "BRIX Travel Website",
      "WhatsApp CRM",
    ],
  },
  {
    nm: "Supabase",
    id: "supabase",
    em: "⚡",
    category: "database-platform",
    dt: "BRIX DB · PostgreSQL",
    lk: "https://supabase.com/dashboard",
    prj: "BRIX Travel System",
    related_entities: ["BRIX Travel System", "Money Manager"],
    used_in: ["BRIX Travel System", "Money Manager"],
  },
  {
    nm: "Vercel",
    id: "vercel",
    em: "▲",
    category: "deployment",
    dt: "BRIX auto-deploy",
    lk: "https://vercel.com",
    prj: "BRIX Travel System",
    used_in: ["BRIX Travel System"],
  },
  {
    nm: "Railway",
    id: "railway",
    em: "🚂",
    category: "deployment",
    dt: "WhatsApp CRM · production",
    lk: "https://railway.app",
    prj: "WhatsApp CRM",
    used_in: ["WhatsApp CRM"],
  },
  {
    nm: "Heroku",
    id: "heroku",
    em: "🟣",
    category: "deployment",
    dt: "Bank Bot · متوقف",
    lk: "https://dashboard.heroku.com",
    prj: "Bank Bot",
    active: false,
    used_in: ["Bank Bot"],
  },
  {
    nm: "Meta Business",
    id: "meta-business",
    em: "📘",
    category: "marketing-platform",
    dt: "EasyBooking Ads",
    lk: "https://business.facebook.com",
    prj: "EasyBooking",
    used_in: ["EasyBooking", "WhatsApp CRM"],
  },
  {
    nm: "Airtable",
    id: "airtable",
    em: "📊",
    category: "data-platform",
    dt: "11 جدول · BRIX SOT",
    lk: "https://airtable.com",
    prj: "BRIX Travel System",
    used_in: ["BRIX Travel System"],
  },
  {
    nm: "Telegram",
    id: "telegram",
    em: "✈️",
    category: "communication",
    dt: "قنوات وبوتات نشطة",
    prj: "Argaz Bot",
    related_entities: ["Argaz Bot", "Claude Code Bot", "Tron Address Bot"],
    used_in: ["Argaz Bot", "Claude Code Bot", "Tron Address Bot"],
  },
  {
    nm: "Contabo VPS",
    id: "contabo-vps",
    em: "🖥️",
    category: "infrastructure",
    dt: "62.171.128.44 · Ubuntu 24",
    prj: "Wapy.dev",
    related_entities: ["Wapy.dev", "Argaz Bot"],
    used_in: ["Wapy.dev", "Argaz Bot"],
  },
  {
    nm: "Hostinger",
    id: "hostinger",
    em: "🌍",
    category: "deployment",
    dt: "استضافة موقع BRIX Travel Website",
    prj: "BRIX Travel Website",
    used_in: ["BRIX Travel Website"],
  },
  {
    nm: "iCloud Drive",
    id: "icloud-drive",
    em: "☁️",
    category: "storage",
    dt: "آلاف الملفات المنظمة المرتبطة بالمشاريع والحملات",
    prj: "EasyBooking",
    related_entities: ["EasyBooking"],
    used_in: ["EasyBooking"],
  },
  {
    nm: "Perplexity",
    id: "perplexity",
    em: "🔍",
    category: "mcp-linked",
    dt: "MCP · بحث عميق",
    prj: "Command Center",
    related_entities: ["Command Center", "Claude Code"],
    used_in: ["Command Center", "Claude Code"],
  },
  {
    nm: "Firecrawl",
    id: "firecrawl",
    em: "🕷️",
    category: "mcp-linked",
    dt: "MCP · زحف ويب",
    prj: "Command Center",
    related_entities: ["Command Center", "Claude Code"],
    used_in: ["Command Center", "Claude Code"],
  },
  {
    nm: "Notion",
    id: "notion",
    em: "📝",
    category: "mcp-linked",
    dt: "MCP · إدارة مهام",
    prj: "Command Center",
    related_entities: ["Command Center", "Claude Code"],
    used_in: ["Command Center", "Claude Code"],
  },
  {
    nm: "Tailscale",
    id: "tailscale",
    em: "🔒",
    category: "network",
    dt: "VPN · 3 أجهزة",
    prj: "Wapy.dev",
    related_entities: ["Wapy.dev", "Argaz Bot", "Command Center"],
    used_in: ["Wapy.dev", "Argaz Bot", "Command Center"],
  },
  {
    nm: "TronGrid",
    id: "trongrid",
    em: "🔗",
    category: "external-api",
    dt: "Blockchain API",
    lk: "https://trongrid.io",
    prj: "Tron Address Bot",
    used_in: ["Tron Address Bot"],
  },
  {
    nm: "CoinGecko",
    id: "coingecko",
    em: "🪙",
    category: "external-api",
    dt: "أسعار كريبتو",
    lk: "https://coingecko.com",
    prj: "Money Manager",
    used_in: ["Money Manager"],
  },
];

const ARC = [
  {
    name: "Exchanger",
    id: "exchanger",
    ar: "منصة صرف العملات",
    kind: "archived-project",
    em: "💱",
    cl: "#F59E0B",
    st: "arc",
    summary: "منصة صرف قديمة محفوظة ككود كامل.",
    next_step: "لا شيء",
    related_projects: [],
    desc: "واجهة ويب لمنصة BoxExchanger — عمل سابق\n\n🔧 التقنيات:\nNuxt.js 2.15 + Express + MongoDB\nDocker · i18n عربي/إنجليزي/روسي\n\n📁 المكونات:\nواجهة العميل (exchanger-client-web)\nبوت تلغرام للعمليات (exchanger-bot)\n\n🔗 Git: boxexchanger.net — private server\n\n📌 الحالة: مجمّد — كود كامل محفوظ",
    tags: ["Nuxt.js 2", "MongoDB", "Docker", "Telegram Bot"],
    path: "/Users/rabeeshaban/Desktop/Archive/💱 Exchanger",
    links: {},
  },
  {
    name: "Etranex",
    id: "etranex",
    ar: "شركة إيترانكس",
    kind: "archived-brand",
    em: "🏢",
    cl: "#6366F1",
    st: "arc",
    summary: "هوية بصرية مؤرشفة لمشروع مغلق.",
    next_step: "أرشيف فقط",
    related_projects: [],
    desc: "شركة صرافة سابقة — هوية بصرية كاملة\n\n📦 المحفوظ:\n+25 نسخة شعار بكل الأحجام والألوان\nفيكتور أصلي + favicon + وثيقة PDF قانونية\n\n📍 محفوظة داخل iCloud Drive ضمن أرشيف-مشاريع/etranex\n\n📌 الحالة: مغلقة — أرشيف هوية فقط",
    tags: ["Branding", "Logo", "Identity"],
    path: "/Users/rabeeshaban/Library/Mobile Documents/com~apple~CloudDocs/📦 أرشيف-مشاريع/etranex",
    links: {},
  },
  {
    name: "Boyner Pipeline",
    id: "boyner-pipeline",
    ar: "بوينر — خط بيانات أزياء",
    kind: "archived-client-work",
    em: "🛍️",
    cl: "#EC4899",
    st: "arc",
    summary: "خط بيانات مكتمل ومسلّم لعميل سابق.",
    next_step: "أرشيف فقط",
    related_projects: [],
    desc: "خط بيانات لاستيراد منتجات Boyner إلى WooCommerce — عميل سابق\n\n🔧 التقنيات:\nPython (pandas) · Docker · WordPress/WooCommerce · MySQL 8\n\n⚙️ السكريبتات:\nweb_enrich_and_download.py — تحميل المنتجات\nprep_clean_and_group.py — تنظيف البيانات\nmake_woo_csv.py — تحويل لـ WooCommerce\n\n🎨 20+ علامة تجارية (Armani, Fendi, Guess...)\n💾 الحجم: 1.2 GB صور منتجات\n\n📌 الحالة: مكتمل — مسلّم للعميل",
    tags: ["Python", "WooCommerce", "Docker", "Web Scraping"],
    path: "/Users/rabeeshaban/Desktop/Archive/boyner",
    links: {},
  },
  {
    name: "BRIX Real Estate",
    id: "brix-real-estate",
    ar: "بريكس العقارية",
    kind: "archived-site-export",
    em: "🏗️",
    cl: "#10B981",
    st: "arc",
    summary: "تصدير كامل لموقع عقاري مغلق.",
    next_step: "أرشيف فقط",
    related_projects: [],
    desc: "موقع عقاري WordPress — تصدير كامل\n\n🔧 البنية:\nWordPress + Houzez Theme\nصفحات عقارية + مدونة\n\n📦 المحفوظ:\nتصدير كامل: wp-admin + wp-content + wp-includes\n1,576+ ملف\n\n📌 الحالة: موقع مغلق — أرشيف كامل",
    tags: ["WordPress", "Houzez", "Real Estate"],
    path: "/Users/rabeeshaban/Desktop/Archive/brix-studio-export",
    links: { المصدر: "https://brixrealstate.wordpress.com" },
  },
  {
    name: "Smart Media Indexer",
    id: "smart-media-indexer",
    ar: "فهرسة الوسائط الذكية",
    kind: "archived-tool",
    em: "📸",
    cl: "#3B82F6",
    st: "arc",
    summary: "أداة فهرسة وسائط استُخدمت مرة واحدة ثم أُرشفت.",
    next_step: "يمكن إعادة استخدامها لاحقًا",
    related_projects: ["EasyBooking"],
    desc: "أداة Python لفهرسة وتصنيف الصور بـ Gemini AI\n\n🔧 التقنيات:\nPython 3.10 + Gemini API + SQLite\n\n⚙️ المكونات:\nscanner.py · metadata_extractor.py\ndatabase.py · reporter.py\n\n📊 النتائج:\n_MASTER_INDEX.db — قاعدة بيانات الصور\ndiscovery_report.html — تقرير مرئي\n\n📌 الحالة: مكتملة — استُخدمت مرة واحدة",
    tags: ["Python", "Gemini AI", "SQLite"],
    path: "/Users/rabeeshaban/Library/Mobile Documents/com~apple~CloudDocs/📦 أرشيف-مشاريع/Smart-Media-Indexer",
    links: {},
  },
  {
    name: "🔐 Vault",
    id: "vault",
    ar: "الخزنة المشفرة",
    kind: "active-security",
    em: "🔐",
    cl: "#EF4444",
    st: "a",
    summary: "مخزن أمني نشط وليس أرشيف مشروع.",
    next_step: "يظل خارج الأرشيف الفعلي",
    related_projects: ["Tron Address Bot"],
    desc: "DMG مشفر AES-256 — 130 ملف حساس\n\n📦 المحتوى:\nمحافظ كريبتو (مفاتيح خاصة)\nرموز 2FA الاحتياطية\nوثائق هوية رقمية\n\n⚠️ لا يُفتح إلا عند الحاجة\n💾 الحجم: 500 MB\n\n📌 الحالة: نشط — يُستخدم ويُحدَّث بانتظام",
    tags: ["AES-256", "Encrypted", "Crypto", "2FA"],
    path: "/Users/rabeeshaban/Desktop/🔐 Vault.dmg",
    links: {},
  },
  {
    name: "Lobster",
    id: "lobster",
    ar: "مكتبة تشغيل الوكلاء",
    kind: "active-runtime",
    em: "🦞",
    cl: "#F97316",
    st: "a",
    summary: "مكتبة تشغيل وكلاء حية على السيرفر، وليست أرشيفًا.",
    next_step: "تبقى ضمن طبقة runtime",
    related_projects: ["Argaz Bot"],
    desc: "ClawdBot — SDK/CLI لتشغيل وكلاء AI على السيرفر\n\n🔧 البنية:\nمكتبة Python محلية (ليست خدمة)\nمثبَّت في: /home/argaz/.local/lobster\n\n⚙️ الاستخدام:\nتشغيل وكلاء OpenClaw\nإدارة مهام AI المجدولة\n\n📌 الحالة: نشط على السيرفر — يشغّل وكلاء OpenClaw",
    tags: ["SDK", "Python", "AI Agents", "CLI"],
    path: "server:/home/argaz/.local/lobster",
    links: {},
  },
];

const IDEAS = [
  {
    name: "بوت تلقرام لبريكس",
    id: "brix-telegram-bot",
    em: "🤖",
    cl: "#0088CC",
    st: "فكرة",
    pr: 2,
    horizon: "قريب",
    owner_scope: "BRIX",
    related_projects: ["Argaz Bot", "BRIX Travel System"],
    next_step: "تحديد MVP للإشعارات والحجوزات",
    summary: "بوت عمليات لبريكس لإشعارات الحجوزات والإدارة السريعة.",
    desc: "بوت تلقرام لإدارة الحجوزات والإشعارات\n\n🔔 إشعارات فورية:\nحجز جديد → إشعار للفريق\nإلغاء → تنبيه عاجل\nتقارير يومية تلقائية\n\n📊 إدارة العمليات:\nعرض الحجوزات الحالية\nتحديث حالة الحجز\nبحث عن عميل\n\n👥 متعدد المستخدمين: مدير + موظفين",
  },
  {
    name: "نظام تتبع مالي",
    id: "brix-financial-tracking",
    em: "💰",
    cl: "#10B981",
    st: "فكرة",
    pr: 1,
    horizon: "عاجل",
    owner_scope: "BRIX + EasyBooking",
    related_projects: ["BRIX Travel System", "Wapy.dev", "Money Manager"],
    next_step: "تحديد نموذج البيانات الموحد بين الصرافة والحجوزات والإعلانات",
    summary: "نظام مالي موحد يربط الصرافة والحجوزات والحملات.",
    desc: "تتبع كل العمليات المالية لـ BRIX TRAVEL\n\n💱 الصرافة (السنتر):\nتسجيل كل عملية صرف\nأسعار الصرف اللحظية\nتقارير يومية/شهرية\n\n🏨 الحجوزات:\nتتبع كل حجز من البداية للنهاية\nحساب العمولات تلقائياً\nتقارير ROAS لكل حملة إعلانية\n\n📊 تقارير موحدة:\nإيرادات الصرافة + الحجوزات\nالمصاريف + الأرباح الصافية\nمقارنة شهرية",
  },
  {
    name: "BRIX Website v2",
    id: "brix-website-v2",
    em: "🌐",
    cl: "#E8453C",
    st: "فكرة",
    pr: 3,
    horizon: "يوماً ما",
    owner_scope: "BRIX",
    related_projects: ["BRIX Travel Website", "BRIX Travel System"],
    next_step: "تحويل الفكرة إلى backlog ميزات واضحة بدل وصف عام",
    summary: "نسخة ثانية من موقع BRIX تربط التسعير بالحجز المباشر.",
    desc: "تطوير موقع بريكس ترافل — حجز أونلاين مباشر\n\n🎯 الرؤية:\nموقع حديث بتصميم عصري\nصفحة لكل فندق مع صور وأسعار\nنظام حجز مباشر (بدون واتساب)\n\n🔗 التكامل:\nربط مع محرك التسعير BRIX\nدفع أونلاين (Stripe/Paddle)\nتأكيد فوري + إيصال بالبريد",
  },
];

const BSTATS = {
  "Tron Address Bot": [
    { v: "AES-256", l: "تشفير" },
    { v: "26", l: "ثغرة أُصلحت" },
    { v: "5", l: "حد محاولات" },
  ],
  "Bank Bot": [
    { v: "OCR", l: "استخراج" },
    { v: "CSV", l: "تصدير" },
    { v: "pandas", l: "تحليل" },
  ],
  "Argaz Bot": [
    { v: "6", l: "نماذج" },
    { v: "13", l: "مهارة" },
    { v: "3", l: "وكلاء" },
    { v: "24/7", l: "متاح" },
  ],
  "Claude Code Bot": [
    { v: "allowlist", l: "وصول" },
    { v: "3", l: "أدوات" },
    { v: "50MB", l: "مرفقات" },
  ],
};
