/* ══════════════════════════════════════════════
   DATA — البيانات فقط، لا دوال هنا
   لتحديث المحتوى: عدّل هذا الملف فقط
   ══════════════════════════════════════════════ */

const PG=[{id:'home',n:'الرئيسية',ic:'🏠'},{id:'projects',n:'المشاريع',ic:'🚀'},{id:'map',n:'الخريطة',ic:'🗺️'},{id:'auto',n:'الأتمتة',ic:'⚙️'},{id:'server',n:'السيرفر',ic:'🖥️'},{id:'bots',n:'البوتات',ic:'🤖'},{id:'tools',n:'الأدوات',ic:'🛠️'},{id:'ideas',n:'الأفكار',ic:'💡'},{id:'cloud',n:'السحابية',ic:'☁️'},{id:'archive',n:'الأرشيف',ic:'🗄️'}];

const PRJ=[
  {name:"BRIX Travel System",id:"brix-travel-system",kind:"product",ar:"نظام حجز الفنادق",st:"a",em:"🏨",cl:"#6C3AED",pct:85,summary:"النظام الرئيسي لإدارة عقود الفنادق والتسعير والبحث والنتائج.",local_path:"/Users/rabeeshaban/Desktop/Projects/🏨 BRIX-Travel/hotel-web-app",server_path:null,repo_url:"https://github.com/aneerabee/brix-travel-system",deploy_url:"https://hotel-web-app-ten.vercel.app",stack:["Next.js 16","TypeScript","Supabase","Vitest","Playwright","Tailwind 4"],subsystems:["pricing-engine","contract-wizard","results-ui","api-layer","alerts-dashboard"],related_services:[],related_tools:[],related_cloud:["GitHub","Supabase","Vercel","Airtable"],ops:["auto-deploy على Vercel","source of truth عبر Supabase/Airtable"],desc:"المشروع الرئيسي — نظام إدارة عقود الفنادق وحساب الأسعار\n\n📐 البنية: LEGO Architecture (7 كتل مستقلة)\ntypes → db → pricing → infra → validation → testing → ui\n\n🔧 التقنيات:\nNext.js 16 + React 18 + TypeScript 5.7 + Tailwind 4\nSupabase (PostgreSQL) + Zod 4 + Vitest + Playwright\n\n📊 الأرقام:\n1,450+ اختبار (وحدة + تكامل + E2E)\n30 مرحلة تطوير مكتملة\n10 خطوات Contract Wizard\n\n🔄 سير البيانات:\nAirtable (11 جدول) → n8n → Supabase → Next.js → واجهة\n\n🚀 النشر: Vercel (تلقائي من GitHub)",tags:["Next.js 16","Supabase","Tailwind 4","Vitest","Playwright","TypeScript"],path:"~/Desktop/Projects/🏨 BRIX-Travel/hotel-web-app/",links:{"الموقع":"https://hotel-web-app-ten.vercel.app","GitHub":"https://github.com/aneerabee/brix-travel-system","Supabase":"https://supabase.com/dashboard/project/fiancnwrfehyrkvfjwfq","Airtable":"https://airtable.com"}},
  {name:"Wedding Planner",id:"wedding-planner",kind:"product",ar:"مخطط الزفاف",st:"a",em:"💒",cl:"#E8453C",pct:70,summary:"تطبيق تخطيط زفاف فعلي بواجهة عميل وخادم Node/SQLite مع نسخ احتياطي مجدول.",local_path:null,server_path:"/home/argaz/wedding-planner",repo_url:null,deploy_url:"http://62.171.128.44:3001",stack:["Vite","Node.js","Express","SQLite"],subsystems:["client","server","backups","tools"],related_services:["Wedding Planner","Reminders Scheduler","Wedding Backup"],related_tools:[],related_cloud:["Contabo VPS","Telegram"],ops:["نسخ احتياطي كل 6 ساعات","تذكيرات مجدولة عبر reminders-scheduler"],desc:"نظام تخطيط حفل الزفاف — 5 أيام (21-25 أبريل 2026)\n\n👥 قائمة الضيوف:\nإضافة/حذف/تعديل ضيوف\nاختيار أيام الحضور لكل ضيف\nوضع تعديل جماعي\n\n🔔 منبهات تلقرام:\nعد تنازلي يومي\nمهام يومية ذكية\nتذكيرات قبل كل يوم\n\n🔧 التقنيات:\nReact 19 + Express.js + SQLite\nSystemd service على السيرفر\n\n💾 نسخ احتياطي كل 6 ساعات\n📡 المنفذ: 3001 على Contabo",tags:["React 19","Express","SQLite","Telegram","systemd"],path:"server:~/wedding-planner/",links:{"التطبيق":"http://62.171.128.44:3001"}},
  {name:"EasyBooking",id:"easybooking",kind:"umbrella",ar:"تسويق إيزي بوكينغ",st:"a",em:"📢",cl:"#2563EB",pct:60,summary:"منظومة تسويق وتشغيل تضم حملات Meta وCRM واتساب وخادم MCP داخلي وأدوات ومحتوى حملات.",local_path:"/Users/rabeeshaban/Desktop/Projects/📢 EasyBooking",server_path:null,repo_url:null,deploy_url:null,stack:["Meta Ads","WhatsApp","Python","MCP","Assets"],subsystems:["whatsapp-crm","meta-mcp","social-tools","docs","sueno-scripts"],related_services:["Chrome Headless"],related_tools:["Meta MCP"],related_cloud:["Meta Business","Railway","GitHub","iCloud Drive"],ops:["إدارة حملات متعددة الأسواق","أصول وصور ومحتوى محفوظة على iCloud"],desc:"ذراع التسويق لـ BRIX TRAVEL — حجوزات فنادق\n\n🎯 الحملة الحالية:\nSueno Deluxe Belek — 6 مناطق\nشمال أفريقيا → الخليج → الشام → عرب تركيا → أوروبا → كندا\n8 كاروسيلات + 5 فيديوهات\nنسخ عربي فقط\n\n📱 القنوات:\nMeta Business Suite + Ads Manager\nWhatsApp كقناة حجز أساسية\nInstagram + Facebook\n\n🛠️ أدوات:\n37 أداة MCP للتحكم بالإعلانات\nSocial Growth Tracker\nحساب: act_840190289038740",tags:["Meta Ads","WhatsApp","6 دول","37 MCP Tools","Instagram"],path:"iCloud:📢 EasyBooking/",links:{"Ads Manager":"https://adsmanager.facebook.com/adsmanager/manage/campaigns?act=840190289038740","Business Suite":"https://business.facebook.com"}},
  {name:"Meta MCP",id:"meta-mcp",kind:"internal-tool",ar:"خادم MCP للإعلانات",st:"a",em:"🤖",cl:"#2563EB",pct:88,summary:"خادم MCP داخلي مطور خصيصًا للتحكم في إعلانات Meta عبر وحدات قراءة وكتابة واستهداف ونسخ وتحويلات.",local_path:"/Users/rabeeshaban/Desktop/Projects/📢 EasyBooking/🤖 meta-mcp",server_path:null,repo_url:"https://github.com/aneerabee/meta-mcp",deploy_url:null,stack:["Python","MCP","httpx","Meta Graph API"],subsystems:["read","write","targeting","duplicate","conversions","utility"],related_services:[],related_tools:["Claude Code"],related_cloud:["GitHub","Meta Business"],parent_project:"EasyBooking",ops:["أداة تشغيل داخلية وليست SaaS","تتحكم بحساب Meta Ads مباشرة"],desc:"خادم MCP داخلي لإدارة إعلانات Meta عبر وحدات مستقلة\n\n📦 الوحدات:\nread.py · write.py · targeting.py\nduplicate.py · conversions.py · utility.py\n\n🔧 التقنيات:\nPython + MCP stdio + httpx\nMeta Graph API\n\n🎯 الاستخدام:\nقراءة الحملات والإعلانات\nإنشاء وتعديل ونسخ الأصول\nإدارة الاستهداف والتحويلات\n\n🔒 الريبو خاص على GitHub",tags:["Python","MCP","Meta Graph API","httpx","Internal Tool"],path:"~/Desktop/Projects/📢 EasyBooking/🤖 meta-mcp/",links:{"GitHub":"https://github.com/aneerabee/meta-mcp"}},
  {name:"Wapy.dev",id:"wapy-dev",kind:"product",ar:"متتبع الاشتراكات",st:"a",em:"💳",cl:"#10B981",pct:55,summary:"تطبيق اشتراكات حي يعمل عبر Docker بثلاث حاويات على السيرفر مع نسخ احتياطي وتنظيف مجدول.",local_path:null,server_path:"/opt/wapy",repo_url:null,deploy_url:"http://100.116.69.101:3000",stack:["Next.js","React","Prisma","PostgreSQL","Paddle","Better Auth","Docker"],subsystems:["app","cron","db","backup","media"],related_services:["Wapy App","Wapy Cron","Wapy DB","Wapy Backup","Wapy Cleanup"],related_tools:[],related_cloud:["Contabo VPS","Tailscale"],ops:["backup يوميًا 3 صباحًا","cleanup يوميًا 4 صباحًا","تشغيل عبر Docker"],desc:"تطبيق تتبع وإدارة الاشتراكات الشهرية\n\n🔧 التقنيات:\nNext.js + Turbopack + TypeScript\nPrisma ORM + PostgreSQL 17.5\nPaddle (دفع) + better-auth (مصادقة)\nTailwind + shadcn/ui\n\n🐳 Docker:\n3 حاويات: app + db + cron\nالمنفذ: 3000 (عبر Tailscale فقط)\n\n💾 النسخ الاحتياطي:\nيومياً 3 صباحاً + تنظيف 4 صباحاً\nاحتفاظ 30 يوم · حد 50 ملف\n\n👤 المؤلف: ربيع · الإصدار: 2.0.0",tags:["Next.js","Prisma","Docker","PostgreSQL","Paddle","shadcn/ui"],path:"server:/opt/wapy/",links:{"التطبيق الداخلي":"http://100.116.69.101:3000"}},
  {name:"Command Center",id:"command-center",kind:"dashboard",ar:"مركز التحكم",st:"a",em:"⚡",cl:"#F59E0B",pct:90,summary:"لوحة تحكم شخصية تعرض المشاريع والخدمات والبوتات والأدوات والسحابية من مكان واحد.",local_path:"/tmp/cc-push",server_path:null,repo_url:"https://github.com/aneerabee/command-center",deploy_url:"https://aneerabee.github.io/command-center/",stack:["HTML","CSS","JavaScript","GitHub Pages"],subsystems:["home","projects","map","auto","server","bots","tools","ideas","cloud","archive"],related_services:[],related_tools:[],related_cloud:["GitHub"],ops:["نشر ثابت عبر GitHub Pages","صفحات متعددة مع render client-side"],desc:"لوحة تحكم واحدة تجمع كل شيء\n\n📄 4 ملفات (HTML + CSS + JS + Data)\n10 صفحات بتصاميم مختلفة\n5 أنماط عرض تفصيلية فريدة\n📱 متجاوب + GitHub Pages",tags:["HTML","CSS","JS","GitHub Pages"],path:"github:aneerabee/command-center",links:{"الموقع":"https://aneerabee.github.io/command-center/","GitHub":"https://github.com/aneerabee/command-center"}},
  {name:"WhatsApp CRM",id:"whatsapp-crm",kind:"service-app",ar:"نظام إدارة العملاء",st:"a",em:"💬",cl:"#25D366",pct:45,summary:"FastAPI backend فعلي لإدارة محادثات واتساب والحجوزات والـ CAPI ضمن منظومة EasyBooking.",local_path:"/Users/rabeeshaban/Desktop/Projects/📢 EasyBooking/💬 whatsapp-crm",server_path:null,repo_url:"https://github.com/aneerabee/easybooking-whatsapp-crm",deploy_url:"https://easybooking-whatsapp-crm-production.up.railway.app/#inbox",stack:["FastAPI","Python","PostgreSQL","Meta CAPI","WhatsApp Cloud API","Docker","Railway"],subsystems:["dashboard","data","config","scripts","tools"],related_services:[],related_tools:[],related_cloud:["Railway","Meta Business","GitHub"],parent_project:"EasyBooking",ops:["production على Railway","API + dashboard + webhooks"],desc:"قلب نظام التحويل — إعلان → واتساب → حجز\n\n🔄 المسار:\nإعلان Meta (CTWA) → نقرة العميل\n→ رسالة واتساب تلقائية (60 ثانية)\n→ 8 قوالب عربية حسب زاوية الإعلان\n→ متابعة → حجز → تتبع ROAS\n\n📊 قاعدة البيانات:\ncontacts · conversations · messages\nbookings · meta_events_log · raw_webhooks\n\n🔧 API: 8 نقاط نهاية + X-API-Key\n\n📈 تتبع التحويلات:\nMeta CAPI مع EMQ scoring\nattribution: إعلان → واتساب → حجز → قيمة\n\n🌍 6 دول: ليبيا، مصر، العراق، تونس، المغرب، الجزائر\n\n🔧 التقنيات:\nFastAPI + PostgreSQL + Meta CAPI\nWhatsApp Cloud API + Docker\nRailway (production)",tags:["FastAPI","Meta CAPI","WhatsApp","Railway","PostgreSQL","Docker"],path:"~/Desktop/Projects/📢 EasyBooking/💬 whatsapp-crm/",links:{"التطبيق":"https://easybooking-whatsapp-crm-production.up.railway.app/#inbox","Railway":"https://railway.app","GitHub":"https://github.com/aneerabee/easybooking-whatsapp-crm"}},
  {name:"Money Manager",id:"money-manager",kind:"financial-app",ar:"مدير المال",st:"p",em:"💰",cl:"#F59E0B",pct:40,summary:"تطبيق/API مالي مستقل مبني بـ FastAPI ومربوط بـ Supabase وأسعار مالية خارجية.",local_path:"/Users/rabeeshaban/Desktop/Projects/💰 Money-Manager",server_path:null,repo_url:"https://github.com/aneerabee/money-manager",deploy_url:null,stack:["FastAPI","Python","Supabase","CoinGecko","Alpha Vantage"],subsystems:["main-api"],related_services:[],related_tools:["Claude Code"],related_cloud:["GitHub","Supabase","CoinGecko"],ops:["مشروع متوقف حاليًا لكنه قائم كمصدر كود فعال","يعتمد على APIs خارجية مالية"],desc:"نظام إدارة مالية شامل\n\n💹 الميزات:\nأسعار كريبتو لحظية (CoinGecko)\nأسعار أسهم (Alpha Vantage)\nCRUD كامل للمعاملات\nتخزين مؤقت ذكي\n\n🔧 التقنيات:\nFastAPI + Python\nSupabase (PostgreSQL)\nCoinGecko + Alpha Vantage APIs\n\n📂 ملف رئيسي: main.py (102 KB)",tags:["FastAPI","Supabase","CoinGecko","Python","Alpha Vantage"],path:"~/Desktop/Projects/💰 Money-Manager/",links:{"GitHub":"https://github.com/aneerabee/money-manager"}},
  {name:"BRIX Travel Website",id:"brix-travel-website",kind:"website",ar:"موقع بريكس ترافل",st:"a",em:"🌐",cl:"#E8453C",pct:30,summary:"موقع WordPress حي للشركة، وليس مجرد static landing page.",local_path:"/Users/rabeeshaban/Desktop/Projects/🌐 brixtravelwebsite",server_path:null,repo_url:"https://github.com/aneerabee/brixtravel",deploy_url:null,stack:["WordPress","PHP","HTML","CSS","JavaScript"],subsystems:["wp-admin","wp-content","wp-includes","assets"],related_services:[],related_tools:[],related_cloud:["GitHub","Hostinger"],ops:["موقع حي يحتاج تحديث محتوى وتطوير واجهة حجز"],desc:"الموقع الرسمي لشركة BRIX TRAVEL — مباشر على Hostinger\n\n🌍 عربي + إنجليزي · اكتشاف تلقائي للغة\n📱 تصميم متجاوب · Google Maps مدمج\nWhatsApp + Instagram + Facebook\n\n🔧 التقنيات:\nHTML/CSS/JS + PHP + WordPress\n\n🎨 الهوية البصرية:\nBrix Travel.ai + .eps (شعار كامل)\n\n🛠️ يحتاج تطوير:\nواجهة حجز مباشرة · تحديث المحتوى\n\n📡 النشر: Hostinger",tags:["WordPress","PHP","Hostinger","HTML","يحتاج تطوير"],path:"~/Desktop/Projects/🌐 brixtravelwebsite/",links:{"GitHub":"https://github.com/aneerabee/brixtravel"}},
  {name:"Chess Academy",id:"chess-academy",kind:"content-product",ar:"أكاديمية الشطرنج",st:"a",em:"♟️",cl:"#d4a843",pct:95,summary:"منتج تعليمي static ثنائي اللغة منشور على GitHub Pages مع نظام تقدم واختبارات.",local_path:null,server_path:null,repo_url:"https://github.com/aneerabee/chess-academy",deploy_url:"https://aneerabee.github.io/chess-academy/",stack:["HTML","CSS","JavaScript","GitHub Pages"],subsystems:["arabic-app","english-app","landing-en","quiz-system","xp-system"],related_services:[],related_tools:[],related_cloud:["GitHub"],ops:["بيع Freemium","نشر مباشر على GitHub Pages"],desc:"دليل شطرنج تفاعلي — عربي + إنجليزي\n\n🔧 التقنيات:\nHTML + CSS + Vanilla JS\nتصميم داكن/ذهبي · بدون خادم\n\n📊 المحتوى:\n6 مراحل × لغتين (عربي + إنجليزي)\n30+ مفهوم وتكتيك\nاختبارات تفاعلية بعد كل مرحلة\nتمارين «فكّر معي» (Think-Along)\n\n🎮 نظام التقدم:\nXP لكل مفهوم واختبار\nسلسلة يومية 🔥\nشاشة إنجاز + شارات\n\n💰 نظام البيع (Freemium):\nمرحلتان مجانيتان + 4 مدفوعة بـ $19\nبوابة وصول SHA-256\nرمز: CHESSMIND2026\n\n🌍 الروابط:\nعربي: /app.html\nإنجليزي: /en.html\nصفحة هبوط EN: /en/\n\n🚀 النشر:\nGitHub Pages",tags:["HTML","CSS","JavaScript","GitHub Pages","Gumroad","AR+EN","Quizzes","XP System"],path:"github:aneerabee/chess-academy",links:{"العربي":"https://aneerabee.github.io/chess-academy/","English":"https://aneerabee.github.io/chess-academy/en.html","GitHub":"https://github.com/aneerabee/chess-academy"}}
];

const SVC=[
  {name:"Wedding Planner",id:"wedding-planner-app",st:1,em:"💒",host:"Contabo VPS",runtime:"Node.js + Express + SQLite",service_type:"app",prj:"Wedding Planner",owner:"Wedding Planner",owner_type:"project",path:"/home/argaz/wedding-planner",port:"3001",schedule:"دائم",dt:"React 19 + Express + SQLite · app",info:"تطبيق إدارة حفل الزفاف — عميل + خادم + SQLite + backups"},
  {name:"Wapy App",id:"wapy-app",st:1,em:"💳",host:"Contabo VPS",runtime:"Docker / Next.js",service_type:"container",prj:"Wapy.dev",owner:"Wapy.dev",owner_type:"project",path:"/opt/wapy",port:"3000",schedule:"دائم",dt:"wapydev-app · Docker container",info:"واجهة Wapy.dev الحية عبر Tailscale"},
  {name:"Wapy Cron",id:"wapy-cron",st:1,em:"⏰",host:"Contabo VPS",runtime:"Docker / Alpine",service_type:"container",prj:"Wapy.dev",owner:"Wapy.dev",owner_type:"project",path:"/opt/wapy",port:"—",schedule:"دائم",dt:"wapydev-cron · Docker container",info:"حاوية cron خاصة بمهام Wapy.dev المجدولة"},
  {name:"Wapy DB",id:"wapy-db",st:1,em:"🗄️",host:"Contabo VPS",runtime:"PostgreSQL 17.5",service_type:"database",prj:"Wapy.dev",owner:"Wapy.dev",owner_type:"project",path:"/opt/wapy/db",port:"5432",schedule:"دائم",dt:"wapydev-db · PostgreSQL 17.5",info:"قاعدة بيانات Wapy.dev مربوطة محليًا على 127.0.0.1"},
  {name:"Argaz Gateway",id:"argaz-gateway",st:1,em:"🤖",host:"Contabo VPS",runtime:"OpenClaw 2026.2.6-3",service_type:"agent-runtime",prj:"",owner:"Argaz Bot",owner_type:"bot",path:"/home/argaz/.openclaw",port:"18789",schedule:"دائم",dt:"OpenClaw gateway + model chain",info:"الـ runtime الرئيسي لـ Argaz والوكلاء المعزولين"},
  {name:"Chrome Headless",id:"chrome-headless",st:1,em:"🌐",host:"Contabo VPS",runtime:"systemd user service",service_type:"user-service",prj:"EasyBooking",owner:"EasyBooking",owner_type:"project",path:"~/.config/systemd/user/chrome-headless.service",port:"—",schedule:"دائم",dt:"Browser automation · systemd",info:"متصفح بدون واجهة يستخدمه OpenClaw والعمليات المؤتمتة"},
  {name:"Reminders Scheduler",id:"reminders-scheduler",st:1,em:"⏰",host:"Contabo VPS",runtime:"systemd user service",service_type:"user-service",prj:"Wedding Planner",owner:"Wedding Planner",owner_type:"project",path:"~/.config/systemd/user/reminders-scheduler.service",port:"—",schedule:"دائم",dt:"reminders-scheduler.service",info:"يرسل تذكيرات الزفاف اليومية عبر Telegram"},
  {name:"Wedding Backup",id:"wedding-backup-cron",st:1,em:"💾",host:"Contabo VPS",runtime:"cron",service_type:"cron",prj:"Wedding Planner",owner:"Wedding Planner",owner_type:"project",path:"/home/argaz/wedding-planner/backup-wedding.sh",port:"—",schedule:"كل 6 ساعات",dt:"0 */6 * * *",info:"نسخ احتياطي دوري لقاعدة بيانات Wedding Planner"},
  {name:"Wapy Backup",id:"wapy-backup-cron",st:1,em:"💾",host:"Contabo VPS",runtime:"cron",service_type:"cron",prj:"Wapy.dev",owner:"Wapy.dev",owner_type:"project",path:"/opt/wapy/scripts/backup.sh",port:"—",schedule:"يوميًا 3 صباحًا",dt:"0 3 * * *",info:"pg/sql backup محفوظ داخل ‎.backup"},
  {name:"Wapy Cleanup",id:"wapy-cleanup-cron",st:1,em:"🧹",host:"Contabo VPS",runtime:"cron",service_type:"cron",prj:"Wapy.dev",owner:"Wapy.dev",owner_type:"project",path:"/opt/wapy/.backup",port:"—",schedule:"يوميًا 4 صباحًا",dt:"0 4 * * *",info:"حذف نسخ Wapy.dev الأقدم من 30 يومًا"},
  {name:"Gateway Watchdog",id:"gateway-watchdog",st:1,em:"🛡️",host:"Contabo VPS",runtime:"cron",service_type:"cron",prj:"",owner:"Argaz Bot",owner_type:"bot",path:"/home/argaz/gateway-watchdog.sh",port:"—",schedule:"كل دقيقة",dt:"* * * * *",info:"يراقب OpenClaw ويعيد التشغيل عند التوقف"},
  {name:"Config Backup",id:"config-backup",st:1,em:"🗂️",host:"Contabo VPS",runtime:"cron",service_type:"cron",prj:"",owner:"Argaz Bot",owner_type:"bot",path:"/home/argaz/backup-config.sh",port:"—",schedule:"كل ساعة",dt:"0 * * * *",info:"يحفظ نسخًا من openclaw.json عند التغيير"},
  {name:"OpenClaw Gateway Service",id:"openclaw-gateway-service",st:0,em:"🔌",host:"Contabo VPS",runtime:"systemd user service",service_type:"user-service",prj:"",owner:"Argaz Bot",owner_type:"bot",path:"~/.config/systemd/user/openclaw-gateway.service",port:"18789",schedule:"موثق كخدمة",dt:"موثق في CLAUDE.md",info:"وحدة systemd موثقة كبنية gateway لكن لم تكن ظاهرة ضمن الخدمات العاملة في لقطة الفحص"},
  {name:"Tailscale VPN",id:"tailscale-vpn",st:1,em:"🔒",host:"متعدد",runtime:"VPN mesh",service_type:"network",prj:"Command Center",owner:"Command Center",owner_type:"project",path:"100.116.69.101",port:"—",schedule:"دائم",dt:"MacBook + iPhone + Server",info:"شبكة VPN خاصة للوصول الآمن إلى الخدمات الداخلية"}
];

const AUTO=[
  {group:"MacBook Pro",loc:"launchd / محلي",host:"desktop",tasks:[
    {name:"auto-backup.sh",freq:"يوميًا 14:00",on:true,what:"دفع meta-mcp + Money Manager + brixtravelwebsite إلى GitHub",prj:["Meta MCP","Money Manager","BRIX Travel Website"],path:"local launchd",kind:"backup"},
    {name:"PM2 Resurrect",freq:"عند الإقلاع",on:true,what:"إعادة تشغيل العمليات المحلية المحفوظة تلقائيًا",prj:["Command Center"],path:"local pm2",kind:"runtime"},
    {name:"BRIX Invoice Server",freq:"دائم",on:true,what:"تشغيل خادم فواتير BRIX محليًا",prj:["BRIX Travel System"],path:"localhost:8000",kind:"app"}
  ]},
  {group:"Contabo VPS",loc:"cron + systemd",host:"server",tasks:[
    {name:"Wedding Planner Backup",freq:"كل 6 ساعات",on:true,what:"نسخ قاعدة SQLite إلى مجلد backups",prj:["Wedding Planner"],path:"/home/argaz/wedding-planner/backup-wedding.sh",kind:"backup"},
    {name:"Wapy.dev DB Dump",freq:"يوميًا 3 صباحًا",on:true,what:"تنفيذ backup لبيانات Wapy.dev",prj:["Wapy.dev"],path:"/opt/wapy/scripts/backup.sh",kind:"backup"},
    {name:"Wapy.dev Cleanup",freq:"يوميًا 4 صباحًا",on:true,what:"تنظيف النسخ القديمة الأقدم من 30 يومًا",prj:["Wapy.dev"],path:"/opt/wapy/.backup",kind:"cleanup"},
    {name:"Argaz Config Backup",freq:"كل ساعة",on:true,what:"حفظ نسخ openclaw.json عند التغييرات",prj:["Argaz Bot"],path:"/home/argaz/backup-config.sh",kind:"backup"},
    {name:"Gateway Watchdog",freq:"كل دقيقة",on:true,what:"مراقبة gateway وإعادة تشغيله عند التوقف",prj:["Argaz Bot"],path:"/home/argaz/gateway-watchdog.sh",kind:"watchdog"}
  ]},
  {group:"Argaz Bot",loc:"OpenClaw Scheduler",host:"server",tasks:[
    {name:"Morning Briefing",freq:"08:00 يوميًا",on:true,what:"Gmail + طقس أنطاليا + ذاكرة → Telegram",prj:["Argaz Bot"],path:"~/.openclaw/workspace",kind:"briefing"},
    {name:"Daily Self-Review",freq:"كل 24 ساعة",on:true,what:"مراجعة التعلمات وتحديث الذاكرة",prj:["Argaz Bot"],path:"~/.openclaw/workspace/MEMORY.md",kind:"memory"},
    {name:"Memory Maintenance",freq:"03:00 كل يومين",on:false,what:"تنظيف وصيانة ملفات الذاكرة",prj:["Argaz Bot"],path:"~/.openclaw/memory",kind:"maintenance"},
    {name:"Weekly Skill Extraction",freq:"أسبوعيًا",on:false,what:"استخراج مهارات جديدة من التعلمات",prj:["Argaz Bot"],path:"~/.openclaw/workspace/.learnings",kind:"learning"},
    {name:"Error Pattern Detection",freq:"كل 3 أيام",on:false,what:"كشف الأنماط المتكررة في الأخطاء",prj:["Argaz Bot"],path:"~/.openclaw/workspace/.learnings/ERRORS.md",kind:"diagnostics"}
  ]},
  {group:"Claude Code",loc:"Hooks",host:"desktop",tasks:[
    {name:"PreToolUse",freq:"3 hooks",on:true,what:"تحقق قبل الأدوات وقيود العمل",prj:["Command Center"],path:"~/.claude",kind:"hook"},
    {name:"PostToolUse",freq:"2 hooks",on:true,what:"تنسيق وفحص بعد الأدوات",prj:["Command Center"],path:"~/.claude",kind:"hook"},
    {name:"Stop",freq:"1 hook",on:true,what:"تحقق نهائي قبل إنهاء الجلسة",prj:["Command Center"],path:"~/.claude",kind:"hook"}
  ]}
];

const BOT=[
  {name:"Tron Address Bot",id:"tron-address-bot",kind:"telegram-bot",ar:"بوت عناوين ترون",st:"a",em:"⚡",cl:"#10B981",host:"محلي",runtime:"Node.js",channel:"Telegram",related_entities:["Vault"],summary:"بوت حساس أمنيًا لإدارة محافظ Tron ومراقبة العناوين.",desc:"بوت Telegram لمراقبة عناوين ترون وإدارة المحافظ\n\n⚡ وضع التشغيل: عند الطلب فقط\nيُشغَّل يدوياً لوقت محدود ثم يُغلق\nالسبب: حساسية البيانات (محافظ + مفاتيح)\n\n🔐 الأمان:\nتشفير AES-256 + كلمة مرور رئيسية\nحد 5 محاولات + قفل 15 دقيقة\nملفات حساسة محمية (600)\n\n🛡️ تدقيق أمني مارس 2026:\n26 ثغرة اكتُشفت وأُصلحت\nتحديث كل المكتبات\nمقارنة كلمة مرور آمنة ضد timing attacks\n\n🚀 التشغيل:\nstart-bot-background.sh",tags:["Node.js","TronWeb","AES-256","On-Demand"],path:"~/Desktop/Projects/🤖 Bots/🕵️ tron-address-bot/"},
  {name:"Bank Bot",id:"bank-bot",kind:"telegram-bot",ar:"بوت كشوف البنك",st:"p",em:"🏦",cl:"#2563EB",host:"سحابي",runtime:"Python",channel:"Telegram",related_entities:["Heroku"],summary:"بوت OCR لتحليل كشوف البنك، متوقف حاليًا.",desc:"بوت Telegram لتحليل كشوف البنك تلقائياً\n\n📸 كيف يعمل:\nأرسل صورة كشف الحساب\nيستخرج البيانات بتقنية OCR\nيحلل التحويلات والأرصدة\n\n📊 التصدير:\nCSV + Excel\nتقارير مفصلة\n\n🔧 التقنيات:\nPython + pytesseract + pandas\nمنشور على Heroku (متوقف حالياً)",tags:["Python","OCR","Heroku","pandas"],path:"~/Desktop/Archive/bank-bot/",links:{"Heroku":"https://dashboard.heroku.com/apps/ruble-transfer-bot"}},
  {name:"Argaz Bot",id:"argaz-bot",kind:"agent-runtime",ar:"بوت أرقاز",st:"a",em:"🧠",cl:"#6C3AED",host:"Contabo VPS",runtime:"OpenClaw 2026.2.6-3",channel:"Telegram @Argaz_clawbot",related_entities:["Lobster","Command Center"],summary:"runtime متعدد الوكلاء مع gateway وmemory وscheduler، وليس بوتًا بسيطًا.",desc:"بوت ذكاء اصطناعي شخصي — OpenClaw 2026.2.6-3\n\n🤖 Telegram: @Argaz_clawbot\nالسيرفر: Contabo · منفذ 18789\nساعات الهدوء: 23:00 – 07:30\n\n🧠 النماذج (بالترتيب):\n1. Gemini 2.5 Flash — الأساسي\n2. LLaMA 3.3-70B (Groq) — الاحتياطي الأول\n3. LLaMA 3.1-8B (Groq) — سريع\n4. Kimi-K2.5 (Moonshot)\n5. Kimi-K2-turbo-preview\n6. MiniMax-M2.1\n\n👥 3 وكلاء مستقلين:\nmain (Argaz) — نشط 24/7\nwork (عامل) — مُعدّ للعمل\nbrix-travel (بريكس) — مُعدّ\n\n🛠️ 13 مهارة:\ncode-generator · reminders-tasks · multi-agent\nclaude-usage · research · memory-manager\nreflect-learn · preprompt · self-improving\nvoice · character + 2 داخلية\n\n⏰ التاسكات السحابية (OpenClaw Cron):\n08:00 يومياً ← morning-briefing\nGmail + طقس أنطاليا + ذاكرة → Telegram\nكل 24 ساعة ← daily-self-review\nمراجعة learnings + تحديث الذاكرة\n03:00 كل يومين ← memory-maintenance\nتنظيف وصيانة ملفات الذاكرة\nأسبوعياً ← weekly-skill-extraction\nاستخراج مهارات جديدة من التعلمات\nكل 3 أيام ← error-pattern-detection\nكشف أنماط الأخطاء المتكررة\n🛡️ حماية النظام (System Cron):\nكل دقيقة ← gateway-watchdog\nمراقبة OpenClaw وإعادة تشغيله تلقائياً\nكل ساعة ← backup-config\nنسخ احتياطي لـ openclaw.json عند التغيير",tags:["Gemini","AI","24/7","OpenClaw","13 Skills","6 Models","5 Cron Jobs"],path:"server:~/.openclaw/"},
  {name:"Claude Code Bot",id:"claude-code-bot",kind:"assistant-channel",ar:"بوت كلاود كود",st:"a",em:"⚡",cl:"#8B5CF6",host:"MacBook",runtime:"Claude Code + plugin",channel:"Telegram",related_entities:["Command Center"],summary:"قناة تحكم عن بُعد بـ Claude Code عبر Telegram.",desc:"بوت Telegram للتحكم بـ Claude Code عن بُعد\n\nPlugin: telegram@claude-plugins-official v0.0.4\nMCP Server — grammy + Bun\n\n📍 الموقع:\n~/.claude/channels/telegram/\n\n🔐 الوصول:\nPolicy: allowlist — مغلق للغرباء\nمسموح: ID واحد فقط (أنت)\nلا تاريخ رسائل · لا بحث\n\n🛠️ أدوات البوت:\nreply — إرسال ردود + مرفقات حتى 50MB\nreact — إيموجي ريأكشن على رسائلك\nedit_message — تعديل رسائل البوت (progress)\n\n📸 الصور الواردة:\nتُحفظ تلقائياً في inbox/ وتُقرأ مباشرة\n\n🚀 التشغيل:\nclaude --channels plugin:telegram@claude-plugins-official\n\n⚠️ لا تاسكات مجدولة — يرد فقط عند مراسلتك",tags:["MCP Server","grammy","Bun","Telegram","Claude Code","allowlist"],path:"~/.claude/channels/telegram/"}
];

const TL=[
{name:"Codex CLI",id:"codex-cli",ar:"إعداد Codex",st:"a",cl:"#0F766E",type:"مستخدمة",category:"developer-env",used_in:["Command Center","BRIX Travel System","EasyBooking"],summary:"بيئة GPT-5.4 الحالية مع تعليمات دائمة وPlugins مفعلة للمستودعات والتصميم.",desc:"Codex يعمل هنا من ~/.codex\n\nالإعدادات المؤكدة من المصدر:\nmodel = gpt-5.4\nreasoning = medium\npersonality = pragmatic\nPlugins مفعلة: GitHub + Canva\nTrusted workspace: /Users/rabeeshaban/Documents/New project\n\nالتخصيص الأهم:\nAGENTS.md صار يحمل معيار العمل الدائم الذي يحدد عدم الكسر والتنظيف وعدم الهلوسة قبل أي تنفيذ.",tags:["gpt-5.4","medium reasoning","GitHub plugin","Canva plugin","AGENTS.md"],path:"/Users/rabeeshaban/.codex/",config_paths:["/Users/rabeeshaban/.codex/config.toml","/Users/rabeeshaban/.codex/AGENTS.md"],facts:["model: gpt-5.4","reasoning: medium","personality: pragmatic","plugins: GitHub + Canva","trusted workspace: /Users/rabeeshaban/Documents/New project"],customizations:["إضافة معيار العمل الدائم داخل AGENTS.md","اعتماد هذا المشروع كـ trusted workspace في config.toml"],structure:["config.toml — النموذج والـ plugins والثقة بالمشاريع","AGENTS.md — التعليمات الدائمة التي نعدلها نحن","plugins/cache/openai-curated — إضافات GitHub وCanva","skills/.system — مهارات النظام الأساسية","logs_1.sqlite + state_5.sqlite — سجلات الحالة والجلسات"],capabilities:["GitHub plugin","Canva plugin","system skills (5 حاليًا)"],edit_points:["عدّل model / reasoning / personality من config.toml","عدّل قواعد العمل الدائمة من AGENTS.md","لا تعدّل cache أو sqlite يدويًا إلا لسبب تقني واضح"],links:{}},
  {name:"Claude Code",id:"claude-code",ar:"إعداد Claude Code",st:"a",cl:"#6C3AED",type:"مستخدمة",category:"developer-env",used_in:["Command Center","BRIX Travel System","EasyBooking"],summary:"بيئة Claude Code الحالية مع Agents وCommands وHooks وPlugins متصلة فعليًا.",desc:"Claude Code يعمل من ~/.claude\n\nالإعدادات المؤكدة من المصدر:\n14 agent files\n44 commands\n49 skills\n3 plugins مفعلة: coderabbit + swift-lsp + telegram\nstatusLine مخصص من ~/.claude/scripts/statusline.sh\n\nالتخصيصات المؤكدة:\nHook قبل git push للمراجعة\nHook بعد تعديل JS لتشغيل prettier\nتنبيه عند وجود console.log\nتشغيل صوت عند Stop",tags:["14 Agents","44 Commands","49 Skills","3 Plugins","Hooks"],path:"/Users/rabeeshaban/.claude/",config_paths:["/Users/rabeeshaban/.claude/settings.json","/Users/rabeeshaban/.claude/settings.local.json","/Users/rabeeshaban/.claude/agents","/Users/rabeeshaban/.claude/commands","/Users/rabeeshaban/.claude/channels"],facts:["agents: 14","commands: 44","skills: 49","plugins: coderabbit + swift-lsp + telegram","statusline: ~/.claude/scripts/statusline.sh","permissions allow list: 23 entries"],customizations:["PreToolUse hook يذكر باستخدام tmux للأوامر الطويلة","PreToolUse hook يراجع git push قبل الدفع","PostToolUse hook يشغل prettier على JS/TS","PostToolUse hook ينبه عند console.log","Stop hook يشغل صوت النظام عند نهاية الجلسة"],structure:["settings.json — الصلاحيات والـ hooks والـ plugins","agents/ — 14 وكيلًا متخصصًا","commands/ — 44 أمرًا جاهزًا","channels/telegram — قناة Telegram لـ Claude Code","projects/ + sessions/ + todos/ — سياق العمل والجلسات والخطط"],capabilities:["telegram plugin","coderabbit plugin","swift-lsp plugin","14 agents","44 commands"],edit_points:["عدّل الصلاحيات والـ plugins والـ hooks من settings.json","عدّل الاستثناءات المحلية من settings.local.json","أضف/عدّل الوكلاء من agents/ والأوامر من commands/","عدّل قناة Telegram من channels/telegram فقط"],links:{}},
  {name:"Meta MCP",id:"meta-mcp-tool",ar:"خادم MCP للإعلانات",st:"a",cl:"#2563EB",type:"مبنية",category:"internal-tool",used_in:["EasyBooking","WhatsApp CRM"],summary:"خادم MCP داخلي للتحكم الكامل بإعلانات Meta",desc:"37 أداة في 6 وحدات — بديل مجاني لـ Pipeboard\nPython + httpx + Meta Graph API v22.0\nحساب: act_840190289038740\n\n🔒 محفوظ على GitHub (خاص)",tags:["37 Tools","MCP","Python"],path:"~/Desktop/Projects/📢 EasyBooking/🤖 meta-mcp/",links:{"GitHub":"https://github.com/aneerabee/meta-mcp"}},
  {name:"GitHub",id:"github-tool",ar:"مستودعات GitHub",st:"a",cl:"#10B981",type:"مستخدمة",category:"platform",used_in:["BRIX Travel System","Meta MCP","Money Manager","BRIX Travel Website","Command Center","WhatsApp CRM","Chess Academy"],summary:"المنصة المركزية للمستودعات والنشر والتاريخ",desc:"حساب: aneerabee — 7 مستودعات مؤكدة في منظومة العمل الحالية\n\nالمشاريع المؤكدة:\ncommand-center — لوحة التحكم\nchess-academy — أكاديمية الشطرنج\nbrix-travel-system — نظام الحجز\neasybooking-whatsapp-crm — CRM واتساب\nmoney-manager — إدارة مالية\nmeta-mcp — خادم MCP للإعلانات\nbrixtravel — موقع بريكس",tags:["7 Repos","Source Control","Deploy History"],links:{"GitHub":"https://github.com/aneerabee"}},
  {name:"Tailscale",id:"tailscale-tool",ar:"شبكة Tailscale الخاصة",st:"a",cl:"#00E5FF",type:"مستخدمة",category:"infra-access",used_in:["Wapy.dev","Argaz Bot","Command Center"],summary:"شبكة VPN الخاصة للوصول إلى الخدمات الداخلية",desc:"شبكة VPN خاصة تربط كل الأجهزة:\nسيرفر Contabo: 100.116.69.101 (نشط)\nMacBook Pro: 100.78.245.115 (نشط)\niPhone 15 Pro Max: 100.97.195.82",tags:["VPN","3 أجهزة","مشفر"]},
  {name:"Notion",id:"notion-mcp",ar:"Notion متصل",st:"a",cl:"#FFF",type:"مستخدمة",category:"mcp",used_in:["Claude Code"],summary:"MCP للوصول إلى Notion وإدارة المعرفة والمهام",desc:"MCP Server متصل بـ Claude Code\nإدارة مشاريع ومهام",tags:["MCP","Notion"]},
  {name:"Perplexity",id:"perplexity-mcp",ar:"بحث Perplexity",st:"a",cl:"#20B2AA",type:"مستخدمة",category:"mcp",used_in:["Claude Code"],summary:"MCP للبحث العميق والاستكشاف",desc:"MCP Server للبحث العميق\nresearch + reason + deep_research",tags:["MCP","Search","AI"]},
  {name:"Filesystem",id:"filesystem-mcp",ar:"نظام الملفات",st:"a",cl:"#8B8B8B",type:"مستخدمة",category:"mcp",used_in:["Claude Code"],summary:"MCP للوصول إلى الملفات محليًا",desc:"MCP Server للوصول إلى نظام الملفات\nقراءة وكتابة وبحث في الملفات",tags:["MCP","Files"]},
  {name:"Memory",id:"memory-mcp",ar:"ذاكرة المعرفة",st:"a",cl:"#FF6B6B",type:"مستخدمة",category:"mcp",used_in:["Claude Code","Argaz Bot"],summary:"MCP لذاكرة الكيانات والعلاقات",desc:"MCP Server — رسم بياني للمعرفة\nكيانات + علاقات + ملاحظات",tags:["MCP","Knowledge Graph"]},
  {name:"Sequential Thinking",id:"sequential-thinking-mcp",ar:"التفكير المتسلسل",st:"a",cl:"#FFD93D",type:"مستخدمة",category:"mcp",used_in:["Claude Code"],summary:"MCP لتحليل المسائل خطوة بخطوة",desc:"MCP Server لسلاسل التفكير المنظمة\nتحليل خطوة بخطوة للمسائل المعقدة",tags:["MCP","Reasoning"]},
  {name:"Firecrawl",id:"firecrawl-mcp",ar:"زحف الويب",st:"a",cl:"#FF4500",type:"مستخدمة",category:"mcp",used_in:["Claude Code"],summary:"MCP لاستخراج الصفحات والزحف",desc:"MCP Server لزحف وكشط صفحات الويب\nبحث + استخراج + خريطة موقع",tags:["MCP","Web Scraping"]},
  {name:"Magic",id:"magic-mcp",ar:"سجل الواجهات",st:"a",cl:"#E040FB",type:"مستخدمة",category:"mcp",used_in:["Claude Code","Command Center"],summary:"MCP لأنماط ومكوّنات الواجهة",desc:"MCP Server — سجل مكونات UI\nبحث واستعراض أنماط التصميم",tags:["MCP","UI Registry"]},
  {name:"Supabase",id:"supabase-mcp",ar:"إدارة قواعد البيانات",st:"a",cl:"#3ECF8E",type:"مستخدمة",category:"mcp",used_in:["BRIX Travel System","Money Manager"],summary:"MCP لإدارة Supabase وقاعدة البيانات",desc:"MCP Server لإدارة Supabase\nSQL + migrations + edge functions + branches",tags:["MCP","Database","PostgreSQL"]},
  {name:"Vercel",id:"vercel-mcp",ar:"إدارة النشر",st:"a",cl:"#000",type:"مستخدمة",category:"mcp",used_in:["BRIX Travel System"],summary:"MCP لإدارة deployments على Vercel",desc:"MCP Server لإدارة نشر التطبيقات على Vercel\nربط مع BRIX Travel System",tags:["MCP","Deployment"]},
  {name:"Railway",id:"railway-mcp",ar:"إدارة النشر",st:"a",cl:"#0B0D0E",type:"مستخدمة",category:"mcp",used_in:["WhatsApp CRM"],summary:"MCP لإدارة deployments على Railway",desc:"MCP Server لإدارة نشر التطبيقات على Railway\nربط مع WhatsApp CRM",tags:["MCP","Deployment"]},
  {name:"TestSprite",id:"testsprite-mcp",ar:"اختبارات آلية",st:"a",cl:"#4CAF50",type:"مستخدمة",category:"mcp",used_in:["BRIX Travel System","Command Center"],summary:"MCP لتشغيل وتتبع الاختبارات",desc:"MCP Server للاختبارات الآلية\nتشغيل ومراقبة الاختبارات",tags:["MCP","Testing"]}
];

const CLD=[
  {nm:"GitHub",id:"github",em:"🐙",category:"platform",dt:"7 repos مؤكدة في منظومة العمل الحالية",lk:"https://github.com/aneerabee",prj:"Command Center",related_entities:["Command Center","BRIX Travel System","Chess Academy","Meta MCP","Money Manager","BRIX Travel Website","WhatsApp CRM"],used_in:["Command Center","BRIX Travel System","Chess Academy","Meta MCP","Money Manager","BRIX Travel Website","WhatsApp CRM"]},
  {nm:"Supabase",id:"supabase",em:"⚡",category:"database-platform",dt:"BRIX DB · PostgreSQL",lk:"https://supabase.com/dashboard",prj:"BRIX Travel System",related_entities:["BRIX Travel System","Money Manager"],used_in:["BRIX Travel System","Money Manager"]},
  {nm:"Vercel",id:"vercel",em:"▲",category:"deployment",dt:"BRIX auto-deploy",lk:"https://vercel.com",prj:"BRIX Travel System",used_in:["BRIX Travel System"]},
  {nm:"Railway",id:"railway",em:"🚂",category:"deployment",dt:"WhatsApp CRM · production",lk:"https://railway.app",prj:"WhatsApp CRM",used_in:["WhatsApp CRM"]},
  {nm:"Heroku",id:"heroku",em:"🟣",category:"deployment",dt:"Bank Bot · متوقف",lk:"https://dashboard.heroku.com",prj:"Bank Bot",active:false,used_in:["Bank Bot"]},
  {nm:"Meta Business",id:"meta-business",em:"📘",category:"marketing-platform",dt:"EasyBooking Ads",lk:"https://business.facebook.com",prj:"EasyBooking",used_in:["EasyBooking","WhatsApp CRM"]},
  {nm:"Airtable",id:"airtable",em:"📊",category:"data-platform",dt:"11 جدول · BRIX SOT",lk:"https://airtable.com",prj:"BRIX Travel System",used_in:["BRIX Travel System"]},
  {nm:"Telegram",id:"telegram",em:"✈️",category:"communication",dt:"قنوات وبوتات نشطة",prj:"Argaz Bot",related_entities:["Argaz Bot","Claude Code Bot","Tron Address Bot"],used_in:["Argaz Bot","Claude Code Bot","Tron Address Bot"]},
  {nm:"Contabo VPS",id:"contabo-vps",em:"🖥️",category:"infrastructure",dt:"62.171.128.44 · Ubuntu 24",prj:"Wapy.dev",related_entities:["Wapy.dev","Wedding Planner","Argaz Bot"],used_in:["Wapy.dev","Wedding Planner","Argaz Bot"]},
  {nm:"Hostinger",id:"hostinger",em:"🌍",category:"deployment",dt:"استضافة موقع BRIX Travel Website",prj:"BRIX Travel Website",used_in:["BRIX Travel Website"]},
  {nm:"iCloud Drive",id:"icloud-drive",em:"☁️",category:"storage",dt:"5,400+ ملف منظم",prj:"EasyBooking",related_entities:["EasyBooking"],used_in:["EasyBooking"]},
  {nm:"Perplexity",id:"perplexity",em:"🔍",category:"mcp-linked",dt:"MCP · بحث عميق",prj:"Command Center",related_entities:["Command Center","Claude Code"],used_in:["Command Center","Claude Code"]},
  {nm:"Firecrawl",id:"firecrawl",em:"🕷️",category:"mcp-linked",dt:"MCP · زحف ويب",prj:"Command Center",related_entities:["Command Center","Claude Code"],used_in:["Command Center","Claude Code"]},
  {nm:"Notion",id:"notion",em:"📝",category:"mcp-linked",dt:"MCP · إدارة مهام",prj:"Command Center",related_entities:["Command Center","Claude Code"],used_in:["Command Center","Claude Code"]},
  {nm:"Google Drive",id:"google-drive",em:"📁",category:"mcp-linked",dt:"MCP · ملفات",prj:"Command Center",related_entities:["Command Center","Claude Code"],used_in:["Command Center","Claude Code"]},
  {nm:"Tailscale",id:"tailscale",em:"🔒",category:"network",dt:"VPN · 3 أجهزة",prj:"Wapy.dev",related_entities:["Wapy.dev","Argaz Bot","Command Center"],used_in:["Wapy.dev","Argaz Bot","Command Center"]},
  {nm:"TronGrid",id:"trongrid",em:"🔗",category:"external-api",dt:"Blockchain API",lk:"https://trongrid.io",prj:"Tron Address Bot",used_in:["Tron Address Bot"]},
  {nm:"CoinGecko",id:"coingecko",em:"🪙",category:"external-api",dt:"أسعار كريبتو",lk:"https://coingecko.com",prj:"Money Manager",used_in:["Money Manager"]}
];

const ARC=[
  {name:"Exchanger",id:"exchanger",ar:"منصة صرف العملات",kind:"archived-project",em:"💱",cl:"#F59E0B",st:"arc",summary:"منصة صرف قديمة محفوظة ككود كامل.",next_step:"لا شيء",related_projects:[],desc:"واجهة ويب لمنصة BoxExchanger — عمل سابق\n\n🔧 التقنيات:\nNuxt.js 2.15 + Express + MongoDB\nDocker · i18n عربي/إنجليزي/روسي\n\n📁 المكونات:\nواجهة العميل (exchanger-client-web)\nبوت تلغرام للعمليات (exchanger-bot)\n\n🔗 Git: boxexchanger.net — private server\n\n📌 الحالة: مجمّد — كود كامل محفوظ",tags:["Nuxt.js 2","MongoDB","Docker","Telegram Bot"],path:"~/Desktop/Archive/💱 Exchanger/",links:{}},
  {name:"Etranex",id:"etranex",ar:"شركة إيترانكس",kind:"archived-brand",em:"🏢",cl:"#6366F1",st:"arc",summary:"هوية بصرية مؤرشفة لمشروع مغلق.",next_step:"أرشيف فقط",related_projects:[],desc:"شركة صرافة سابقة — هوية بصرية كاملة\n\n📦 المحفوظ:\n+25 نسخة شعار بكل الأحجام والألوان\nفيكتور أصلي + favicon + وثيقة PDF قانونية\n\n📍 iCloud/أرشيف-مشاريع/etranex/\n\n📌 الحالة: مغلقة — أرشيف هوية فقط",tags:["Branding","Logo","Identity"],path:"iCloud/📦 أرشيف-مشاريع/etranex/",links:{}},
  {name:"Boyner Pipeline",id:"boyner-pipeline",ar:"بوينر — خط بيانات أزياء",kind:"archived-client-work",em:"🛍️",cl:"#EC4899",st:"arc",summary:"خط بيانات مكتمل ومسلّم لعميل سابق.",next_step:"أرشيف فقط",related_projects:[],desc:"خط بيانات لاستيراد منتجات Boyner إلى WooCommerce — عميل سابق\n\n🔧 التقنيات:\nPython (pandas) · Docker · WordPress/WooCommerce · MySQL 8\n\n⚙️ السكريبتات:\nweb_enrich_and_download.py — تحميل المنتجات\nprep_clean_and_group.py — تنظيف البيانات\nmake_woo_csv.py — تحويل لـ WooCommerce\n\n🎨 20+ علامة تجارية (Armani, Fendi, Guess...)\n💾 الحجم: 1.2 GB صور منتجات\n\n📌 الحالة: مكتمل — مسلّم للعميل",tags:["Python","WooCommerce","Docker","Web Scraping"],path:"~/Desktop/Archive/boyner/",links:{}},
  {name:"BRIX Real Estate",id:"brix-real-estate",ar:"بريكس العقارية",kind:"archived-site-export",em:"🏗️",cl:"#10B981",st:"arc",summary:"تصدير كامل لموقع عقاري مغلق.",next_step:"أرشيف فقط",related_projects:[],desc:"موقع عقاري WordPress — تصدير كامل\n\n🔧 البنية:\nWordPress + Houzez Theme\nصفحات عقارية + مدونة\n\n📦 المحفوظ:\nتصدير كامل: wp-admin + wp-content + wp-includes\n1,576+ ملف\n\n📌 الحالة: موقع مغلق — أرشيف كامل",tags:["WordPress","Houzez","Real Estate"],path:"~/Desktop/Archive/brix-studio-export/",links:{"المصدر":"https://brixrealstate.wordpress.com"}},
  {name:"Smart Media Indexer",id:"smart-media-indexer",ar:"فهرسة الوسائط الذكية",kind:"archived-tool",em:"📸",cl:"#3B82F6",st:"arc",summary:"أداة فهرسة وسائط استُخدمت مرة واحدة ثم أُرشفت.",next_step:"يمكن إعادة استخدامها لاحقًا",related_projects:["EasyBooking"],desc:"أداة Python لفهرسة وتصنيف الصور بـ Gemini AI\n\n🔧 التقنيات:\nPython 3.10 + Gemini API + SQLite\n\n⚙️ المكونات:\nscanner.py · metadata_extractor.py\ndatabase.py · reporter.py\n\n📊 النتائج:\n_MASTER_INDEX.db — قاعدة بيانات الصور\ndiscovery_report.html — تقرير مرئي\n\n📌 الحالة: مكتملة — استُخدمت مرة واحدة",tags:["Python","Gemini AI","SQLite"],path:"iCloud/📦 أرشيف-مشاريع/Smart-Media-Indexer/",links:{}},
  {name:"🔐 Vault",id:"vault",ar:"الخزنة المشفرة",kind:"active-security",em:"🔐",cl:"#EF4444",st:"a",summary:"مخزن أمني نشط وليس أرشيف مشروع.",next_step:"يظل خارج الأرشيف الفعلي",related_projects:["Tron Address Bot"],desc:"DMG مشفر AES-256 — 130 ملف حساس\n\n📦 المحتوى:\nمحافظ كريبتو (مفاتيح خاصة)\nرموز 2FA الاحتياطية\nوثائق هوية رقمية\n\n⚠️ لا يُفتح إلا عند الحاجة\n💾 الحجم: 500 MB\n\n📌 الحالة: نشط — يُستخدم ويُحدَّث بانتظام",tags:["AES-256","Encrypted","Crypto","2FA"],path:"~/Desktop/🔐 Vault.dmg",links:{}},
  {name:"Lobster",id:"lobster",ar:"مكتبة تشغيل الوكلاء",kind:"active-runtime",em:"🦞",cl:"#F97316",st:"a",summary:"مكتبة تشغيل وكلاء حية على السيرفر، وليست أرشيفًا.",next_step:"تبقى ضمن طبقة runtime",related_projects:["Argaz Bot"],desc:"ClawdBot — SDK/CLI لتشغيل وكلاء AI على السيرفر\n\n🔧 البنية:\nمكتبة Python محلية (ليست خدمة)\nمثبَّت في: ~/.local/lobster/\n\n⚙️ الاستخدام:\nتشغيل وكلاء OpenClaw\nإدارة مهام AI المجدولة\n\n📌 الحالة: نشط على السيرفر — يشغّل وكلاء OpenClaw",tags:["SDK","Python","AI Agents","CLI"],path:"server:~/.local/lobster/",links:{}}
];

const IDEAS=[
  {name:"بوت تلقرام لبريكس",id:"brix-telegram-bot",em:"🤖",cl:"#0088CC",st:"فكرة",pr:2,horizon:"قريب",owner_scope:"BRIX",related_projects:["Argaz Bot","BRIX Travel System"],next_step:"تحديد MVP للإشعارات والحجوزات",summary:"بوت عمليات لبريكس لإشعارات الحجوزات والإدارة السريعة.",desc:"بوت تلقرام لإدارة الحجوزات والإشعارات\n\n🔔 إشعارات فورية:\nحجز جديد → إشعار للفريق\nإلغاء → تنبيه عاجل\nتقارير يومية تلقائية\n\n📊 إدارة العمليات:\nعرض الحجوزات الحالية\nتحديث حالة الحجز\nبحث عن عميل\n\n👥 متعدد المستخدمين: مدير + موظفين"},
  {name:"نظام تتبع مالي",id:"brix-financial-tracking",em:"💰",cl:"#10B981",st:"فكرة",pr:1,horizon:"عاجل",owner_scope:"BRIX + EasyBooking",related_projects:["BRIX Travel System","Wapy.dev","Money Manager"],next_step:"تحديد نموذج البيانات الموحد بين الصرافة والحجوزات والإعلانات",summary:"نظام مالي موحد يربط الصرافة والحجوزات والحملات.",desc:"تتبع كل العمليات المالية لـ BRIX TRAVEL\n\n💱 الصرافة (السنتر):\nتسجيل كل عملية صرف\nأسعار الصرف اللحظية\nتقارير يومية/شهرية\n\n🏨 الحجوزات:\nتتبع كل حجز من البداية للنهاية\nحساب العمولات تلقائياً\nتقارير ROAS لكل حملة إعلانية\n\n📊 تقارير موحدة:\nإيرادات الصرافة + الحجوزات\nالمصاريف + الأرباح الصافية\nمقارنة شهرية"},
  {name:"BRIX Website v2",id:"brix-website-v2",em:"🌐",cl:"#E8453C",st:"فكرة",pr:3,horizon:"يوماً ما",owner_scope:"BRIX",related_projects:["BRIX Travel Website","BRIX Travel System"],next_step:"تحويل الفكرة إلى backlog ميزات واضحة بدل وصف عام",summary:"نسخة ثانية من موقع BRIX تربط التسعير بالحجز المباشر.",desc:"تطوير موقع بريكس ترافل — حجز أونلاين مباشر\n\n🎯 الرؤية:\nموقع حديث بتصميم عصري\nصفحة لكل فندق مع صور وأسعار\nنظام حجز مباشر (بدون واتساب)\n\n🔗 التكامل:\nربط مع محرك التسعير BRIX\nدفع أونلاين (Stripe/Paddle)\nتأكيد فوري + إيصال بالبريد"}
];

const BSTATS={"Tron Address Bot":[{v:"AES-256",l:"تشفير"},{v:"26",l:"ثغرة أُصلحت"},{v:"5",l:"حد محاولات"}],"Bank Bot":[{v:"OCR",l:"استخراج"},{v:"CSV",l:"تصدير"},{v:"pandas",l:"تحليل"}],"Argaz Bot":[{v:"6",l:"نماذج"},{v:"13",l:"مهارة"},{v:"3",l:"وكلاء"},{v:"24/7",l:"متاح"}],"Claude Code Bot":[{v:"allowlist",l:"وصول"},{v:"3",l:"أدوات"},{v:"50MB",l:"مرفقات"}]};
